"""
This type stub file was generated by pyright.
"""

"""Utils to configure pySMT.

The following is an example of configuration file.

[global]
use_infix_notation: true
solver_preference_list: msat z3 cvc5 z3-smt mathsat-smt

[smtlibsolver z3-smt]
command: z3 -smt2 -in
logics: QF_UFLIRA UFLIRA


[smtlibsolver mathsat-smt]
command: mathsat
logics: QF_UFLIRA



Wrapper solvers are defined using the smtlibsolver section + the name
of the solver.
"""

def configure_environment(config_filename, environment):  # -> None:
    """
    Reads a configuration file from the given path and configures the
    given environment accordingly.
    """
    ...

def write_environment_configuration(config_filename, environment):  # -> None:
    """
    Dumps the configuration of the given environment to the specified
    file. The file can then be re-read with the :py:func:`configure_environment`
    function.

    """
    ...
