"""
This type stub file was generated by pyright.
"""

class deprecated:
    """This is a decorator which can be used to mark functions
    as deprecated. It will result in a warning being emitted
    when the function is used."""
    def __init__(self, alternative=...) -> None: ...
    def __call__(self, func):  # -> Callable[..., Any]:
        ...

def clear_pending_pop(f):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Pop the solver stack (if necessary) before calling the function.

    Some functions (e.g., get_value) required the state of the solver
    to stay unchanged after a call to solve. Therefore, we can leave
    th solver in an intermediate state in which there is a formula
    asserted in the stack that is not needed (e.g., when solving under
    assumptions). In order to guarantee that methods operate on the
    correct set of formulae, all methods of the solver that rely on
    the assertion stack, need to be marked with this decorator.
    """
    ...

def typecheck_result(f):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], None]:
    """Performs type checking on the return value using the global environment"""
    ...

def catch_conversion_error(f):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Catch unknown operators errors and converts them into conversion error."""
    ...

def assert_infix_enabled(f):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Raise an exception if infix notation is not enabled."""
    ...
