"""
This type stub file was generated by pyright.
"""

import pysmt.formula
import pysmt.oracles
import pysmt.printers
import pysmt.simplifier
import pysmt.substituter
import pysmt.type_checker
import pysmt.typing

"""
The Environment is a key structure in pySMT. It contains multiple
singleton objects that are used throughout the system, such as the
FormulaManager, Simplifier, HRSerializer, SimpleTypeChecker.
"""

class Environment:
    """The Environment provides global singleton instances of various objects.

    FormulaManager and the TypeChecker are among the most commonly used ones.

    Subclasses of Environment should take care of adjusting the list
    of classes for the different services, by changing the class
    attributes.
    """

    TypeCheckerClass = pysmt.type_checker.SimpleTypeChecker
    FormulaManagerClass = pysmt.formula.FormulaManager
    TypeManagerClass = pysmt.typing.TypeManager
    SimplifierClass = pysmt.simplifier.Simplifier
    SubstituterClass = pysmt.substituter.MGSubstituter
    HRSerializerClass = pysmt.printers.HRSerializer
    QuantifierOracleClass = pysmt.oracles.QuantifierOracle
    TheoryOracleClass = pysmt.oracles.TheoryOracle
    FreeVarsOracleClass = pysmt.oracles.FreeVarsOracle
    SizeOracleClass = pysmt.oracles.SizeOracle
    AtomsOracleClass = pysmt.oracles.AtomsOracle
    TypesOracleClass = pysmt.oracles.TypesOracle
    def __init__(self) -> None: ...
    @property
    def formula_manager(self):  # -> FormulaManagerClass:
        ...
    @property
    def type_manager(self):  # -> TypeManagerClass:
        ...
    @property
    def simplifier(self):  # -> SimplifierClass:
        ...
    @property
    def serializer(self):  # -> HRSerializerClass:
        ...
    @property
    def substituter(self):  # -> SubstituterClass:
        ...
    @property
    def stc(self):  # -> TypeCheckerClass:
        """Get the Simple Type Checker"""
        ...

    @property
    def qfo(self):  # -> QuantifierOracleClass:
        """Get the Quantifier Oracle"""
        ...

    @property
    def ao(self):  # -> AtomsOracleClass:
        """Get the Atoms Oracle"""
        ...

    @property
    def theoryo(self):  # -> TheoryOracleClass:
        """Get the Theory Oracle"""
        ...

    @property
    def typeso(self):  # -> TypesOracleClass:
        """Get the Types Oracle"""
        ...

    @property
    def fvo(self):  # -> FreeVarsOracleClass:
        """Get the FreeVars Oracle"""
        ...

    @property
    def sizeo(self):  # -> SizeOracleClass:
        """Get the Size Oracle"""
        ...

    def add_dynamic_walker_function(self, nodetype, walker, function):  # -> None:
        """Dynamically bind the given function to the walker for the nodetype.

        This function enables the extension of walkers for new
        nodetypes. When introducing a new nodetype, we link a new
        function to a given walker, so that the walker will be able to
        handle the new nodetype.

        See :py:meth:`pysmt.walkers.generic.Walker.walk_error` for
        more information.
        """
        ...

    @property
    def factory(self):  # -> Factory:
        ...
    def __enter__(self):  # -> Self:
        """Entering a Context"""
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        """Remove environment from global stack."""
        ...

ENVIRONMENTS_STACK = ...

def get_env():
    """Returns the Environment at the head of the stack."""
    ...

def push_env(env=...):  # -> None:
    """Push a env in the stack. If env is None, a new Environment is created."""
    ...

def pop_env():
    """Pop an env from the stack."""
    ...

def reset_env():
    """Destroys and recreate the head environment."""
    ...
