"""
This type stub file was generated by pyright.
"""

"""This module contains all custom exceptions of pySMT."""

class PysmtException(Exception):
    """Base class for all custom exceptions of pySMT"""

    ...

class UnknownSmtLibCommandError(PysmtException):
    """Raised when the parser finds an unknown command."""

    ...

class SolverReturnedUnknownResultError(PysmtException):
    """This exception is raised if a solver returns 'unknown' as a result"""

    ...

class UnknownSolverAnswerError(PysmtException):
    """Raised when the a solver returns an invalid response."""

    ...

class NoSolverAvailableError(PysmtException):
    """No solver is available for the selected Logic."""

    ...

class NonLinearError(PysmtException):
    """The provided expression is not linear."""

    ...

class UndefinedLogicError(PysmtException):
    """This exception is raised if an undefined Logic is attempted to be used."""

    ...

class InternalSolverError(PysmtException):
    """Generic exception to capture errors provided by a solver."""

    ...

class NoLogicAvailableError(PysmtException):
    """Generic exception to capture errors caused by missing support for logics."""

    ...

class SolverRedefinitionError(PysmtException):
    """Exception representing errors caused by multiple definition of solvers
    having the same name."""

    ...

class SolverNotConfiguredForUnsatCoresError(PysmtException):
    """
    Exception raised if a solver not configured for generating unsat
    cores is required to produce a core.
    """

    ...

class SolverStatusError(PysmtException):
    """
    Exception raised if a method requiring a specific solver status is
    incorrectly called in the wrong status.
    """

    ...

class ConvertExpressionError(PysmtException):
    """Exception raised if the converter cannot convert an expression."""
    def __init__(self, message=..., expression=...) -> None: ...
    def __str__(self) -> str: ...

class UnsupportedOperatorError(PysmtException):
    """The expression contains an operator that is not supported.

    The argument node_type contains the unsupported operator id.
    """
    def __init__(self, message=..., node_type=..., expression=...) -> None: ...
    def __str__(self) -> str: ...

class SolverAPINotFound(PysmtException):
    """The Python API of the selected solver cannot be found."""

    ...

class UndefinedSymbolError(PysmtException):
    """The given Symbol is not in the FormulaManager."""
    def __init__(self, name) -> None: ...
    def __str__(self) -> str: ...

class PysmtModeError(PysmtException):
    """The current mode is not supported for this operation"""

    ...

class PysmtImportError(PysmtException, ImportError): ...
class PysmtValueError(PysmtException, ValueError): ...
class PysmtTypeError(PysmtException, TypeError): ...

class PysmtSyntaxError(PysmtException, SyntaxError):
    def __init__(self, message, pos_info=...) -> None: ...
    def __str__(self) -> str: ...

class PysmtIOError(PysmtException, IOError): ...
