"""
This type stub file was generated by pyright.
"""

"""Factories are used to build new Solvers or Quantifier Eliminators
without the need of specifying them. For example, the user can simply
require a Solver that is able to deal with quantified theories, and
the factory will return one such solver among the available ones.
This makes it possible to write algorithms that do not depend on a
particular solver.
"""
DEFAULT_SOLVER_PREFERENCE_LIST = ...
DEFAULT_QELIM_PREFERENCE_LIST = ...
DEFAULT_INTERPOLATION_PREFERENCE_LIST = ...
DEFAULT_LOGIC = ...
DEFAULT_QE_LOGIC = ...
DEFAULT_INTERPOLATION_LOGIC = ...

class Factory:
    """Factory used to build Solver, QuantifierEliminators, Interpolators etc.

    This class contains the logic to magically select the correct
    solver. Moreover, this is the class providing the shortcuts
    is_sat, is_unsat etc.

    """
    def __init__(
        self, environment, solver_preference_list=..., qelim_preference_list=..., interpolation_preference_list=...
    ) -> None: ...
    def get_solver(self, name=..., logic=..., **options): ...
    def get_unsat_core_solver(self, name=..., logic=..., unsat_cores_mode=..., **options): ...
    def get_quantifier_eliminator(self, name=..., logic=...): ...
    def get_interpolator(self, name=..., logic=...): ...
    def add_generic_solver(self, name, args, logics, unsat_core_support=...):  # -> None:
        ...
    def is_generic_solver(self, name):  # -> bool:
        ...
    def get_generic_solver_info(self, name): ...
    def set_solver_preference_list(self, preference_list):  # -> None:
        """Defines the order in which to pick the solvers.

        The list is not required to contain all the solvers. It is
        possible to define a subsets of the solvers, or even just
        one. The impact of this, is that the solver will never be
        selected automatically. Note, however, that the solver can
        still be selected by calling it by name.
        """
        ...

    def set_qelim_preference_list(self, preference_list):  # -> None:
        """Defines the order in which to pick the solvers."""
        ...

    def set_interpolation_preference_list(self, preference_list):  # -> None:
        """Defines the order in which to pick the solvers."""
        ...

    def all_solvers(self, logic=...):  # -> dict[Any, Any]:
        """
        Returns a dict <solver_name, solver_class> including all and only
        the solvers directly or indirectly supporting the given logic.
        A solver supports a logic if either the given logic is
        declared in the LOGICS class field or if a logic subsuming the
        given logic is declared in the LOGICS class field.

        If logic is None, the map will contain all the known solvers
        """
        ...

    def has_solvers(self, logic=...):  # -> bool:
        """
        Returns true if self.all_solvers(logic) is non-empty
        """
        ...

    def all_quantifier_eliminators(self, logic=...):  # -> dict[Any, Any]:
        """Returns a dict <qelim_name, qelim_class> including all and only the
        quantifier eliminators directly or indirectly supporting the
        given logic.  A qelim supports a logic if either the given
        logic is declared in the LOGICS class field or if a logic
        subsuming the given logic is declared in the LOGICS class
        field.

        If logic is None, the map will contain all the known
        quantifier eliminators
        """
        ...

    def all_unsat_core_solvers(self, logic=...):  # -> dict[Any, Any]:
        """
        Returns a dict <solver_name, solver_class> including all and only
        the solvers supporting unsat core extraction and directly or
        indirectly supporting the given logic.  A solver supports a
        logic if either the given logic is declared in the LOGICS
        class field or if a logic subsuming the given logic is
        declared in the LOGICS class field.

        If logic is None, the map will contain all the known solvers
        """
        ...

    def all_interpolators(self, logic=...):  # -> dict[Any, Any]:
        """
        Returns a dict <solver_name, solver_class> including all and only
        the solvers supporting interpolation and directly or
        indirectly supporting the given logic.  A solver supports a
        logic if either the given logic is declared in the LOGICS
        class field or if a logic subsuming the given logic is
        declared in the LOGICS class field.

        If logic is None, the map will contain all the known solvers
        """
        ...

    def Solver(self, name=..., logic=..., **options): ...
    def UnsatCoreSolver(self, name=..., logic=..., unsat_cores_mode=..., **options): ...
    def QuantifierEliminator(self, name=..., logic=...): ...
    def Interpolator(self, name=..., logic=...): ...
    def is_sat(self, formula, solver_name=..., logic=..., portfolio=...): ...
    def get_model(self, formula, solver_name=..., logic=...):  # -> None:
        ...
    def get_implicant(self, formula, solver_name=..., logic=...):  # -> None:
        ...
    def get_unsat_core(self, clauses, solver_name=..., logic=...):  # -> None:
        ...
    def is_valid(self, formula, solver_name=..., logic=..., portfolio=...):  # -> bool:
        ...
    def is_unsat(self, formula, solver_name=..., logic=..., portfolio=...):  # -> bool:
        ...
    def qelim(self, formula, solver_name=..., logic=...): ...
    def binary_interpolant(self, formula_a, formula_b, solver_name=..., logic=...): ...
    def sequence_interpolant(self, formulas, solver_name=..., logic=...): ...
    @property
    def default_logic(self):  # -> Logic:
        ...
    @default_logic.setter
    def default_logic(self, value):  # -> None:
        ...
    @property
    def default_qe_logic(self):  # -> Logic:
        ...
    @default_qe_logic.setter
    def default_qe_logic(self, value):  # -> None:
        ...

ENV_SOLVER_LIST = ...
if ENV_SOLVER_LIST is not None: ...
