"""
This type stub file was generated by pyright.
"""

import sys

from pysmt.walkers.identitydag import IdentityDagWalker

"""The FormulaManager is used to create formulae.

All objects are memoized so that two syntactically equivalent formulae
are represented by the same object.

The FormulaManager provides many more constructors than the operators
defined (operators.py). This is because many operators are rewritten,
and therefore are only virtual. Common examples are GE, GT that are
rewritten as LE and LT. Similarly, the operator Xor is rewritten using
its definition.
"""
if sys.version_info >= (3, 3): ...
else: ...

class FormulaManager:
    """FormulaManager is responsible for the creation of all formulae."""
    def __init__(self, env=...) -> None: ...
    def create_node(self, node_type, args, payload=...):  # -> FNode:
        ...
    def new_fresh_symbol(self, typename, base=...):  # -> FNode:
        ...
    def get_symbol(self, name): ...
    def get_all_symbols(self):  # -> dict_values[Any, Any]:
        ...
    def get_or_create_symbol(self, name, typename):  # -> FNode:
        ...
    def Symbol(self, name, typename=...):  # -> FNode:
        ...
    def FreshSymbol(self, typename=..., template=...):  # -> FNode:
        ...
    def ForAll(self, variables, formula):  # -> FNode:
        """Creates an expression of the form:
            Forall variables. formula(variables)

        Restrictions:
         - Formula must be of boolean type
         - Variables must be BOOL, REAL or INT
        """
        ...

    def Exists(self, variables, formula):  # -> FNode:
        """Creates an expression of the form:
            Exists variables. formula(variables)

        Restrictions:
         - Formula must be of boolean type
         - Variables must be BOOL, REAL or INT
        """
        ...

    def Function(self, vname, params):  # -> FNode:
        """Returns the function application of vname to params.

        Note: Applying a 0-arity function returns the function itself.
        """
        ...

    def Not(self, formula):  # -> FNode:
        """Creates an expression of the form:
            not formula

        Restriction: Formula must be of boolean type
        """
        ...

    def Implies(self, left, right):  # -> FNode:
        """Creates an expression of the form:
            left -> right

        Restriction: Left and Right must be of boolean type
        """
        ...

    def Iff(self, left, right):  # -> FNode:
        """Creates an expression of the form:
            left <-> right

        Restriction: Left and Right must be of boolean type
        """
        ...

    def Minus(self, left, right):  # -> FNode:
        """Creates an expression of the form:
            left - right

        Restriction: Left and Right must be both INT or REAL type
        """
        ...

    def Times(self, *args):  # -> FNode:
        """Creates a multiplication of terms

        This function has polymorphic n-arguments:
          - Times(a,b,c)
          - Times([a,b,c])

        Restriction:
         - Arguments must be all of the same type
         - Arguments must be INT or REAL
        """
        ...

    def Pow(self, base, exponent):  # -> FNode:
        """Creates the n-th power of the base.

        The exponent must be a constant.
        """
        ...

    def Div(self, left, right):  # -> FNode:
        """Creates an expression of the form: left / right"""
        ...

    def Equals(self, left, right):  # -> FNode:
        """Creates an expression of the form: left = right

        For the boolean case use Iff
        """
        ...

    def NotEquals(self, left, right):  # -> FNode:
        """Creates an expression of the form: left != right"""
        ...

    def GE(self, left, right):  # -> FNode:
        """Creates an expression of the form:
            left >= right

        Restriction: Left and Right must be both REAL or INT type
        """
        ...

    def GT(self, left, right):  # -> FNode:
        """Creates an expression of the form:
            left > right

        Restriction: Left and Right must be both REAL or INT type
        """
        ...

    def LE(self, left, right):  # -> FNode:
        """Creates an expression of the form:
            left <= right

        Restriction: Left and Right must be both REAL or INT type
        """
        ...

    def LT(self, left, right):  # -> FNode:
        """Creates an expression of the form:
            left < right

        Restriction: Left and Right must be both REAL or INT type
        """
        ...

    def Ite(self, iff, left, right):  # -> FNode:
        """Creates an expression of the form:
            if( iff ) then  left  else  right

        Restriction:
          - Iff must be BOOL
          - Left and Right must be both of the same type
        """
        ...

    def Real(self, value):  # -> FNode:
        """Returns a Real-type constant of the given value.

        value can be:
          - A Fraction(n,d)
          - A tuple (n,d)
          - A long or int n
          - A float
          - (Optionally) a mpq or mpz object
        """
        ...

    def Int(self, value):  # -> FNode:
        """Return a constant of type INT."""
        ...

    def String(self, value):  # -> FNode:
        """Return a constant of type STRING."""
        ...

    def TRUE(self):  # -> FNode:
        """Return the boolean constant True."""
        ...

    def FALSE(self):  # -> FNode:
        """Return the boolean constant False."""
        ...

    def Bool(self, value):  # -> FNode:
        ...
    def And(self, *args):  # -> FNode:
        """Returns a conjunction of terms.

        This function has polymorphic arguments:
          - And(a,b,c)
          - And([a,b,c])

        Restriction: Arguments must be boolean
        """
        ...

    def Or(self, *args):  # -> FNode:
        """Returns an disjunction of terms.

        This function has polymorphic n-arguments:
          - Or(a,b,c)
          - Or([a,b,c])

        Restriction: Arguments must be boolean
        """
        ...

    def Plus(self, *args):  # -> FNode:
        """Returns an sum of terms.

        This function has polymorphic n-arguments:
          - Plus(a,b,c)
          - Plus([a,b,c])

        Restriction:
         - Arguments must be all of the same type
         - Arguments must be INT or REAL
        """
        ...

    def ToReal(self, formula):  # -> FNode:
        """Cast a formula to real type."""
        ...

    def AtMostOne(self, *args):  # -> FNode:
        """At most one of the bool expressions can be true at anytime.

        This using a quadratic encoding:
           A -> !(B \\/ C)
           B -> !(C)
        """
        ...

    def ExactlyOne(self, *args):  # -> FNode:
        """Encodes an exactly-one constraint on the boolean symbols.

        This using a quadratic encoding:
           A \\/ B \\/ C
           A -> !(B \\/ C)
           B -> !(C)
        """
        ...

    def AllDifferent(self, *args):  # -> FNode:
        """Encodes the 'all-different' constraint using two possible
        encodings.

        AllDifferent(x, y, z) := (x != y) & (x != z) & (y != z)
        """
        ...

    def Xor(self, left, right):  # -> FNode:
        """Returns the xor of left and right: left XOR right"""
        ...

    def Min(self, *args):  # -> FNode:
        """Returns the encoding of the minimum expression within args"""
        ...

    def Max(self, *args):  # -> FNode:
        """Returns the encoding of the maximum expression within args"""
        ...

    def EqualsOrIff(self, left, right):  # -> FNode:
        """Returns Equals() or Iff() depending on the type of the arguments.

        This can be used to deal with ambiguous cases where we might be
        dealing with both Theory and Boolean atoms.
        """
        ...

    def BV(self, value, width=...):  # -> FNode:
        """Return a constant of type BitVector.

        value can be either:
        - a string of 0s and 1s
        - a string starting with "#b" followed by a sequence of 0s and 1s
        - an integer number s.t. 0 <= value < 2**width

        In order to create the BV representation of a signed integer,
        the SBV() method shall be used.
        """
        ...

    def SBV(self, value, width=...):  # -> FNode:
        """Returns a constant of type BitVector interpreting the sign.

        If the specified value is an integer, it is converted in the
        2-complement representation of the given number, otherwise the
        behavior is the same as BV().
        """
        ...

    def BVOne(self, width):  # -> FNode:
        """Returns the bit-vector representing the unsigned one."""
        ...

    def BVZero(self, width):  # -> FNode:
        """Returns the bit-vector with all bits set to zero."""
        ...

    def BVNot(self, formula):  # -> FNode:
        """Returns the bitvector Not(bv)"""
        ...

    def BVAnd(self, *args):  # -> FNode:
        """Returns the Bit-wise AND of bitvectors of the same size.
        If more than 2 arguments are passed, a left-associative formula is generated."""
        ...

    def BVOr(self, *args):  # -> FNode:
        """Returns the Bit-wise OR of bitvectors of the same size.
        If more than 2 arguments are passed, a left-associative formula is generated."""
        ...

    def BVXor(self, left, right):  # -> FNode:
        """Returns the Bit-wise XOR of two bitvectors of the same size."""
        ...

    def BVConcat(self, *args):  # -> FNode:
        """Returns the Concatenation of the given BVs"""
        ...

    def BVExtract(self, formula, start=..., end=...):  # -> FNode:
        """Returns the slice of formula from start to end (inclusive)."""
        ...

    def BVULT(self, left, right):  # -> FNode:
        """Returns the formula left < right."""
        ...

    def BVUGT(self, left, right):  # -> FNode:
        """Returns the formula left > right."""
        ...

    def BVULE(self, left, right):  # -> FNode:
        """Returns the formula left <= right."""
        ...

    def BVUGE(self, left, right):  # -> FNode:
        """Returns the formula left >= right."""
        ...

    def BVNeg(self, formula):  # -> FNode:
        """Returns the arithmetic negation of the BV."""
        ...

    def BVAdd(self, *args):  # -> FNode:
        """Returns the sum of BV.
        If more than 2 arguments are passed, a left-associative formula is generated."""
        ...

    def BVSub(self, left, right):  # -> FNode:
        """Returns the difference of two BV."""
        ...

    def BVMul(self, *args):  # -> FNode:
        """Returns the product of BV.
        If more than 2 arguments are passed, a left-associative formula is generated."""
        ...

    def BVUDiv(self, left, right):  # -> FNode:
        """Returns the division of the two BV."""
        ...

    def BVURem(self, left, right):  # -> FNode:
        """Returns the remainder of the two BV."""
        ...

    def BVLShl(self, left, right):  # -> FNode:
        """Returns the logical left shift the BV."""
        ...

    def BVLShr(self, left, right):  # -> FNode:
        """Returns the logical right shift the BV."""
        ...

    def BVRol(self, formula, steps):  # -> FNode:
        """Returns the LEFT rotation of the BV by the number of steps."""
        ...

    def BVRor(self, formula, steps):  # -> FNode:
        """Returns the RIGHT rotation of the BV by the number of steps."""
        ...

    def BVZExt(self, formula, increase):  # -> FNode:
        """Returns the extension of the BV with 'increase' additional bits

        New bits are set to zero.
        """
        ...

    def BVSExt(self, formula, increase):  # -> FNode:
        """Returns the signed extension of the BV with 'increase' additional bits

        New bits are set according to the most-significant-bit.
        """
        ...

    def BVSLT(self, left, right):  # -> FNode:
        """Returns the SIGNED LOWER-THAN comparison for BV."""
        ...

    def BVSLE(self, left, right):  # -> FNode:
        """Returns the SIGNED LOWER-THAN-OR-EQUAL-TO comparison for BV."""
        ...

    def BVComp(self, left, right):  # -> FNode:
        """Returns a BV of size 1 equal to 0 if left is equal to right,
        otherwise 1 is returned."""
        ...

    def BVSDiv(self, left, right):  # -> FNode:
        """Returns the SIGNED DIVISION of left by right"""
        ...

    def BVSRem(self, left, right):  # -> FNode:
        """Returns the SIGNED REMAINDER of left divided by right"""
        ...

    def BVAShr(self, left, right):  # -> FNode:
        """Returns the RIGHT arithmetic rotation of the left BV by the number
        of steps specified by the right BV."""
        ...

    def BVNand(self, left, right):  # -> FNode:
        """Returns the NAND composition of left and right."""
        ...

    def BVNor(self, left, right):  # -> FNode:
        """Returns the NOR composition of left and right."""
        ...

    def BVXnor(self, left, right):  # -> FNode:
        """Returns the XNOR composition of left and right."""
        ...

    def BVSGT(self, left, right):  # -> FNode:
        """Returns the SIGNED GREATER-THAN comparison for BV."""
        ...

    def BVSGE(self, left, right):  # -> FNode:
        """Returns the SIGNED GREATER-THAN-OR-EQUAL-TO comparison for BV."""
        ...

    def BVSMod(self, left, right):  # -> FNode:
        """Returns the SIGNED MODULUS of left divided by right."""
        ...

    def BVRepeat(self, formula, count=...):  # -> FNode:
        """Returns the concatenation of count copies of formula."""
        ...

    def StrLength(self, formula):  # -> FNode:
        """Returns the length of a formula resulting a String"""
        ...

    def StrConcat(self, *args):  # -> FNode:
        """Returns the concatenation of n Strings.

        s1, s2, ..., and sn are String terms.
        String concatenation takes at least 2 arguments.
        """
        ...

    def StrContains(self, s, t):  # -> FNode:
        """Returns wether the String s contains the String t.

        s and t are String terms.
        """
        ...

    def StrIndexOf(self, s, t, i):  # -> FNode:
        """Returns the position of the first occurrence of t in s after the index i.

        s and t being a non empty strings and i a non-negative integer.
        It returns -1 if the value to search for never occurs.
        """
        ...

    def StrReplace(self, s, t1, t2):  # -> FNode:
        """Returns a new string where the first occurrence of t1 is replace by t2.

        where s, t1 and t2 are string terms, t1 is non-empty.
        """
        ...

    def StrSubstr(self, s, i, j):  # -> FNode:
        """Returns a substring of s starting at i and ending at j+i.

        where s is a string term and i, j are integer terms.
        """
        ...

    def StrPrefixOf(self, s, t):  # -> FNode:
        """Returns whether the s is a prefix of the string t.

        where s and t are string terms.
        """
        ...

    def StrSuffixOf(self, s, t):  # -> FNode:
        """Returns whether the string s is a suffix of the string t.

        where s and t are string terms.
        """
        ...

    def StrToInt(self, s):  # -> FNode:
        """Returns the corresponding natural number of s.

        If s does not represent a natural number, it returns -1.
        """
        ...

    def IntToStr(self, x):  # -> FNode:
        """Returns the corresponding String representing the natural number x.

        where x is an integer term. If x is not a natural number it
        returns the empty String.
        """
        ...

    def StrCharAt(self, s, i):  # -> FNode:
        """Returns a single character String at position i.

        s is a string term and i is an integer term. i is the position.
        """
        ...

    def BVToNatural(self, formula):  # -> FNode:
        """Returns the Natural number represented by the BitVector.

        Given a BitVector of width m returns an integer between 0 and 2^m-1
        """
        ...

    def Select(self, arr, idx):  # -> FNode:
        """Creates a node representing an array selection."""
        ...

    def Store(self, arr, idx, val):  # -> FNode:
        """Creates a node representing an array update."""
        ...

    def Array(self, idx_type, default, assigned_values=...):  # -> FNode:
        """Creates a node representing an array having index type equal to
        idx_type, initialized with default values.

        If assigned_values is specified, then it must be a map from
        constants of type idx_type to values of the same type as
        default and the array is initialized correspondingly.
        """
        ...

    def normalize(self, formula):
        """Returns the formula normalized to the current Formula Manager.

        This method is useful to contextualize a formula coming from another
        formula manager.

        E.g., f_a is defined with the FormulaManager a, and we want to
              obtain f_b that is the formula f_a expressed on the
              FormulaManager b : f_b = b.normalize(f_a)
        """
        ...

    def __contains__(self, node):  # -> Literal[False]:
        """Checks whether the given node belongs to this formula manager.

        This overloads the 'in' operator, making it possible to write:

           E.g., if x in formula_manager: ...
        """
        ...

class FormulaContextualizer(IdentityDagWalker):
    """Helper class to recreate a formula within a new environment."""
    def __init__(self, env=...) -> None: ...
    def walk_symbol(self, formula, args, **kwargs): ...
    def walk_array_value(self, formula, args, **kwargs): ...
    def walk_function(self, formula, args, **kwargs): ...
