"""
This type stub file was generated by pyright.
"""

import pysmt.operators as op
import pysmt.walkers as walkers

"""This module provides classes used to analyze and determine
properties of formulae.

 * SizeOracle provides metrics about the formula
 * QuantifierOracle says whether a formula is quantifier free
 * TheoryOracle says which logic is used in the formula.
 * FreeVarsOracle provides variables that are free in the formula
 * AtomsOracle provides the set of boolean atoms in the formula
 * TypesOracle provides the list of types in the formula
"""

class SizeOracle(walkers.DagWalker):
    """Evaluates the size of a formula"""
    def __init__(self, env=...) -> None: ...
    def set_walking_measure(self, measure):  # -> None:
        ...
    def get_size(self, formula, measure=...):  # -> int:
        """Return the size of the formula according to the specified measure.

        The default measure is MEASURE_TREE_NODES.
        """
        ...

    def walk_count_tree(self, formula, args, **kwargs):  # -> int:
        ...
    def walk_count_dag(self, formula, args, measure, **kwargs):  # -> frozenset[Any]:
        ...
    def walk_count_leaves(self, formula, args, measure, **kwargs):  # -> int:
        ...
    def walk_count_depth(self, formula, args, measure, **kwargs):  # -> int:
        ...
    def walk_count_symbols(self, formula, args, measure, **kwargs):  # -> frozenset[Any]:
        ...
    def walk_count_bool_dag(self, formula, args, measure, **kwargs):  # -> frozenset[Any]:
        ...

class QuantifierOracle(walkers.DagWalker):
    def is_qf(self, formula):
        """Returns whether formula is Quantifier Free."""
        ...

    @walkers.handles(set(op.ALL_TYPES) - op.QUANTIFIERS)
    def walk_all(self, formula, args, **kwargs):  # -> bool:
        ...
    @walkers.handles(op.QUANTIFIERS)
    def walk_false(self, formula, args, **kwargs):  # -> Literal[False]:
        ...

class TheoryOracle(walkers.DagWalker):
    def get_theory(self, formula):
        """Returns the theory for the formula."""
        ...

    @walkers.handles(op.RELATIONS)
    @walkers.handles(op.BOOL_OPERATORS)
    @walkers.handles(op.BV_OPERATORS)
    @walkers.handles(op.STR_OPERATORS - set([op.STR_LENGTH, op.STR_INDEXOF, op.STR_TO_INT]))
    @walkers.handles(op.ITE, op.ARRAY_SELECT, op.ARRAY_STORE, op.MINUS)
    def walk_combine(self, formula, args, **kwargs):
        """Combines the current theory value of the children"""
        ...

    @walkers.handles(op.REAL_CONSTANT, op.BOOL_CONSTANT)
    @walkers.handles(op.INT_CONSTANT, op.BV_CONSTANT)
    @walkers.handles(op.ALGEBRAIC_CONSTANT)
    @walkers.handles(op.STR_CONSTANT)
    def walk_constant(self, formula, args, **kwargs):  # -> Theory:
        """Returns a new theory object with the type of the constant."""
        ...

    def walk_symbol(self, formula, args, **kwargs):  # -> Theory:
        """Returns a new theory object with the type of the symbol."""
        ...

    def walk_function(self, formula, args, **kwargs):
        """Extends the Theory with UF."""
        ...

    def walk_toreal(self, formula, args, **kwargs):
        """Extends the Theory with LIRA."""
        ...

    @walkers.handles([op.STR_LENGTH, op.STR_INDEXOF, op.STR_TO_INT])
    def walk_str_int(self, formula, args, **kwargs): ...
    def walk_bv_tonatural(self, formula, args, **kwargs):
        """Extends the Theory with Integer."""
        ...

    def walk_times(self, formula, args, **kwargs):
        """Extends the Theory with Non-Linear, if needed."""
        ...

    def walk_pow(self, formula, args, **kwargs): ...
    def walk_plus(self, formula, args, **kwargs): ...
    def walk_strings(self, formula, args, **kwargs):  # -> Theory:
        """Extends the Theory with Strings."""
        ...

    def walk_array_value(self, formula, args, **kwargs): ...
    def walk_div(self, formula, args, **kwargs):
        """Extends the Theory with Non-Linear, if needed."""
        ...

DEPENDENCIES_SIMPLE_ARGS = ...

class FreeVarsOracle(walkers.DagWalker):
    def get_free_variables(self, formula):
        """Returns the set of Symbols appearing free in the formula."""
        ...

    @walkers.handles(DEPENDENCIES_SIMPLE_ARGS)
    def walk_simple_args(self, formula, args, **kwargs):  # -> frozenset[Any]:
        ...
    @walkers.handles(op.QUANTIFIERS)
    def walk_quantifier(self, formula, args, **kwargs): ...
    def walk_symbol(self, formula, args, **kwargs):  # -> frozenset[Any]:
        ...
    @walkers.handles(op.CONSTANTS)
    def walk_constant(self, formula, args, **kwargs):  # -> frozenset[Any]:
        ...
    def walk_function(self, formula, args, **kwargs):  # -> frozenset[Any]:
        ...

class AtomsOracle(walkers.DagWalker):
    """This class returns the set of Boolean atoms involved in a formula
    A boolean atom is either a boolean variable or a theory atom
    """
    def get_atoms(self, formula):
        """Returns the set of atoms appearing in the formula."""
        ...

    @walkers.handles(op.BOOL_CONNECTIVES)
    @walkers.handles(op.QUANTIFIERS)
    def walk_bool_op(self, formula, args, **kwargs):  # -> frozenset[Any]:
        ...
    @walkers.handles(op.RELATIONS)
    def walk_theory_relation(self, formula, **kwargs):  # -> frozenset[Any]:
        ...
    @walkers.handles(op.THEORY_OPERATORS - op.ARRAY_SELECT)
    def walk_theory_op(self, formula, **kwargs):  # -> None:
        ...
    def walk_array_select(self, formula, **kwargs):  # -> frozenset[Any] | None:
        ...
    @walkers.handles(op.CONSTANTS)
    def walk_constant(self, formula, **kwargs):  # -> frozenset[Any] | None:
        ...
    def walk_symbol(self, formula, **kwargs):  # -> frozenset[Any] | None:
        ...
    def walk_function(self, formula, **kwargs):  # -> frozenset[Any] | None:
        ...
    def walk_ite(self, formula, args, **kwargs):  # -> frozenset[Any] | None:
        ...

class TypesOracle(walkers.DagWalker):
    def get_types(self, formula, custom_only=...):  # -> list[Any]:
        """Returns the types appearing in the formula.

        custom_only: filter the result by excluding base SMT-LIB types.
        """
        ...

    def expand_types(self, types):  # -> list[Any]:
        """Recursively look into composite types.

        Note: This returns a list. The list is ordered (by
        construction) by having simpler types first)
        """
        ...

    @walkers.handles(set(op.ALL_TYPES) - set([op.SYMBOL, op.FUNCTION]) - op.QUANTIFIERS - op.CONSTANTS)
    def walk_combine(self, formula, args, **kwargs):  # -> frozenset[Any]:
        ...
    @walkers.handles(op.SYMBOL)
    def walk_symbol(self, formula, **kwargs):  # -> frozenset[Any]:
        ...
    @walkers.handles(op.FUNCTION)
    def walk_function(self, formula, **kwargs):  # -> frozenset[Any]:
        ...
    @walkers.handles(op.QUANTIFIERS)
    def walk_quantifier(self, formula, args, **kwargs): ...
    @walkers.handles(op.CONSTANTS)
    def walk_constant(self, formula, args, **kwargs):  # -> frozenset[Any]:
        ...

def get_logic(formula, env=...): ...
