"""
This type stub file was generated by pyright.
"""

import pysmt.operators as op
from pysmt.walkers import DagWalker, IdentityDagWalker, handles

"""
This module defines some rewritings for pySMT formulae.
"""

class CNFizer(DagWalker):
    THEORY_PLACEHOLDER = ...
    TRUE_CNF = ...
    FALSE_CNF = ...
    def __init__(self, environment=...) -> None: ...
    def convert(self, formula):  # -> frozenset[frozenset[Any]]:
        """Convert formula into an Equisatisfiable CNF.

        Returns a set of clauses: a set of set of literals.
        """
        ...

    def convert_as_formula(self, formula):
        """Convert formula into an Equisatisfiable CNF.

        Returns an FNode.
        """
        ...

    def serialize(self, _cnf):  # -> str:
        ...
    @handles(op.QUANTIFIERS)
    def walk_quantifier(self, formula, args, **kwargs): ...
    def walk_and(self, formula, args, **kwargs):  # -> tuple[Any, frozenset[frozenset[Any]]]:
        ...
    def walk_or(self, formula, args, **kwargs):  # -> tuple[Any, frozenset[frozenset[Any]]]:
        ...
    def walk_not(self, formula, args, **kwargs):  # -> tuple[Any, frozenset[Any]] | tuple[Any, Any]:
        ...
    def walk_implies(self, formula, args, **kwargs):  # -> tuple[Any, Any]:
        ...
    def walk_iff(self, formula, args, **kwargs):  # -> tuple[Any, Any]:
        ...
    def walk_symbol(self, formula, **kwargs):  # -> tuple[Any, frozenset[Any]] | Literal['__Placeholder__']:
        ...
    def walk_function(self, formula, **kwargs):  # -> tuple[Any, frozenset[Any]] | Literal['__Placeholder__']:
        ...
    def walk_ite(self, formula, args, **kwargs):  # -> tuple[Any, Any] | Literal['__Placeholder__']:
        ...
    @handles(op.THEORY_OPERATORS)
    def walk_theory_op(self, formula, **kwargs):  # -> Literal['__Placeholder__']:
        ...
    @handles(op.CONSTANTS)
    def walk_constant(self, formula, **kwargs):  # -> tuple[Any, frozenset[Any]] | Literal['__Placeholder__']:
        ...
    @handles(op.RELATIONS)
    def walk_theory_relation(self, formula, args, **kwargs):  # -> tuple[Any, frozenset[Any]]:
        ...

class NNFizer(DagWalker):
    """Converts a formula into Negation Normal Form.

    The conversion to NNF is handled in 3 steps.

    1. The function _get_children is extended, so that for each
    expression inside a Not, it will return the effect of propagating
    the Not downwards. For example, for Not(And(a, b)), the function
    will return [Not(a), Not(b)].  For expressions that are not inside
    a Not, it is important to return the same type of arguments. See
    for example the case for Iff.

    2. The usual walk_* function is implemented to rebuild the
    expression. This is called only if the subformula was not negated.

    3. walk_not takes care of rebuilding all negated expressions. For
    example, for Not(And(a, b)), walk_not will return
    Or(Not(a), Not(b)). Notice that args in walk_not contains the
    subexpressions returned by _get_children.  In the above example,
    walk_not will be called with args=[Not(a), Not(b)]. Therefore,
    walk_not only need to change the And into a Not.

    """
    def __init__(self, environment=...) -> None: ...
    def convert(self, formula):
        """Converts the given formula in NNF"""
        ...

    def walk_not(self, formula, args, **kwargs): ...
    def walk_implies(self, formula, args, **kwargs): ...
    def walk_iff(self, formula, args, **kwargs): ...
    def walk_and(self, formula, args, **kwargs): ...
    def walk_or(self, formula, args, **kwargs): ...
    def walk_ite(self, formula, args, **kwargs): ...
    def walk_forall(self, formula, args, **kwargs): ...
    def walk_exists(self, formula, args, **kwargs): ...
    def walk_symbol(self, formula, **kwargs): ...
    def walk_function(self, formula, **kwargs): ...
    @handles(op.CONSTANTS)
    def walk_constant(self, formula, **kwargs): ...
    @handles(op.RELATIONS)
    def walk_theory_relation(self, formula, **kwargs): ...
    @handles(op.THEORY_OPERATORS)
    def walk_theory_op(self, formula, **kwargs):  # -> None:
        ...

class PrenexNormalizer(DagWalker):
    """
    This class traverses a formula and rebuilds it in prenex normal form.
    """
    def __init__(self, env=..., invalidate_memoization=...) -> None: ...
    def normalize(self, formula): ...
    def walk_symbol(self, formula, **kwargs):  # -> tuple[list[Any], Any] | None:
        ...
    @handles(op.CONSTANTS)
    def walk_constant(self, formula, **kwargs):  # -> tuple[list[Any], Any] | None:
        ...
    @handles(op.AND, op.OR)
    def walk_conj_disj(self, formula, args, **kwargs):  # -> tuple[list[Any], Any] | None:
        ...
    def walk_not(self, formula, args, **kwargs):  # -> tuple[list[tuple[Any, Any]], Any]:
        ...
    def walk_iff(self, formula, args, **kwargs):  # -> tuple[list[Any], Any] | None:
        ...
    def walk_implies(self, formula, args, **kwargs):  # -> tuple[list[Any], Any] | None:
        ...
    def walk_ite(self, formula, args, **kwargs):  # -> tuple[list[Any], Any] | None:
        ...
    def walk_function(self, formula, **kwargs):  # -> tuple[list[Any], Any] | None:
        ...
    @handles(op.RELATIONS)
    def walk_theory_relation(self, formula, **kwargs):  # -> tuple[list[Any], Any]:
        ...
    @handles(op.QUANTIFIERS)
    def walk_quantifier(self, formula, args, **kwargs):  # -> tuple[Any, Any]:
        ...
    @handles(op.THEORY_OPERATORS)
    def walk_theory_op(self, formula, **kwargs):  # -> None:
        ...

class AIGer(DagWalker):
    """Converts a formula into an And-Inverted-Graph."""
    def __init__(self, environment=...) -> None: ...
    def convert(self, formula):
        """Converts the given formula in AIG"""
        ...

    @handles(op.RELATIONS)
    @handles(op.THEORY_OPERATORS)
    @handles(op.CONSTANTS)
    @handles(op.SYMBOL, op.FUNCTION)
    def walk_nop(self, formula, args, **kwargs):
        """We return the Theory subformulae without changes."""
        ...

    @handles(op.QUANTIFIERS)
    def walk_quantifier(self, formula, args, **kwargs):
        """Recreate the quantifiers, with the rewritten subformula."""
        ...

    def walk_and(self, formula, args, **kwargs): ...
    def walk_not(self, formula, args, **kwargs): ...
    def walk_or(self, formula, args, **kwargs):
        """a1 | ... | an = !( !a1 & ... & !an)"""
        ...

    def walk_iff(self, formula, args, **kwargs):
        """a <-> b =  (!a | b) & (!b | a) = !( a & !b ) & !(b & !a)"""
        ...

    def walk_implies(self, formula, args, **kwargs):
        """a -> b = !(a & !b)"""
        ...

    def walk_ite(self, formula, args, **kwargs):
        """This rewrites only boolean ITE, not theory ones.

        x ? a: b  = (x -> a) & (!x -> b) = !(x & !a) & !(!x & !b)
        """
        ...

class TimesDistributor(IdentityDagWalker):
    """Normalize the use of multiplication by pushing it into the leafs.

    E.g., (x+1)*3 -> (x*3) + 3
    """
    def __init__(self, env=..., invalidate_memoization=...) -> None: ...
    def walk_times(self, formula, args, **kwargs):
        """
        From (x + 1) * (y - 1) * p * (m + (7 - p))
        Create [[x, 1], [y, -1*1], [p], [m, 7, -1*p]]
        Compute the cartesian product (itertools.product)

        """
        ...

    def walk_plus(self, formula, args, **kwargs): ...
    def walk_minus(self, formula, args, **kwargs): ...

class Ackermannizer(IdentityDagWalker):
    def __init__(self, environment=...) -> None: ...
    def do_ackermannization(self, formula): ...
    def get_term_to_const_dict(self):  # -> dict[Any, Any]:
        ...
    def get_const_to_term_dict(self):  # -> dict[Any, Any]:
        ...
    def walk_function(self, formula, args, **kwargs): ...

class DisjointSet:
    """A simple implementation of the DisjointSet data-structure.

    It supports also ranking-based DisjointSet and it can be enabled
    by:

    1. defining a binary compare function for the  to be stored in
    a DisjointSet.

    2. Set the compare function while creating the DisjointSet object.
    """
    def __init__(self, compare_fun=...) -> None: ...
    def add(self, a, b):  # -> None:
        """Add the pair (a,b) in the set"""
        ...

    def find(self, k):
        """Find the root of k in the set"""
        ...

def nnf(formula, environment=...):
    """Converts the given formula in NNF"""
    ...

def cnf(formula, environment=...):
    """Converts the given formula in CNF represented as a formula"""
    ...

def cnf_as_set(formula, environment=...):  # -> frozenset[frozenset[Any]]:
    """Converts the given formula in CNF represented as a set of sets"""
    ...

def prenex_normal_form(formula, environment=...):
    """Converts the given formula in Prenex Normal Form"""
    ...

def aig(formula, environment=...):
    """Converts the given formula in AIG"""
    ...

def conjunctive_partition(formula):  # -> Generator[Any, Any, None]:
    """Returns a generator over the top-level conjuncts of the given formula

    The result is such that for every formula phi, the following holds:
    phi <-> And(conjunctive_partition(phi))
    """
    ...

def disjunctive_partition(formula):  # -> Generator[Any, Any, None]:
    """Returns a generator over the top-level disjuncts of the given formula

    The result is such that for every formula phi, the following holds:
    phi <-> Or(conjunctive_partition(phi))
    """
    ...

def propagate_toplevel(formula, env=..., do_simplify=..., preserve_equivalence=...):
    """Propagates the toplevel definitions and returns an equivalent formula.
    It considers three kinds of definitions:
    1) variable = constant
    2) variable = variable
    3) constant = constant
    """
    ...
