"""
This type stub file was generated by pyright.
"""

"""Provides the most used functions in a nicely wrapped API.

This module defines a global environment, so that most methods can be
called without the need to specify an environment or a FormulaManager.
Functions trying to access the global environment should use the
method get_env(). Keep in mind that the global state of the
environment might lead to inconsistency and unexpected bugs. This is
particularly true for tests. For tests it is recommended to perform an
environment reset in the setUp phase, to be guaranteed that a fresh
environment is used (this is the default behavior of
:py:class:`pysmt.test.TestCase` ).
"""
from fractions import Fraction
from typing import Any, Collection, Iterable, Optional, Union

from pysmt.environment import Environment
from pysmt.fnode import FNode
from pysmt.typing import PySMTType

def get_env() -> Environment:
    """Returns the global environment.

    :returns: The global environment
    :rtype: Environment
    """
    ...

def reset_env() -> Environment:
    """Resets the global environment, and returns the new one.

    :returns: A new environment after resetting the global environment
    :rtype: Environment
    """
    ...

def get_type(formula: FNode) -> PySMTType:
    """Returns the type of the formula.

    :param formula: The target formula
    :type  formula: FNode
    :returns: The type of the formula
    """
    ...

def simplify(formula: FNode) -> FNode:
    """Returns the simplified version of the formula.

    :param formula: The target formula
    :type  formula: FNode
    :returns: The simplified version of the formula
    :rtype: Fnode
    """
    ...

def substitute(formula: FNode, subs: dict[FNode, FNode]) -> FNode:
    """Applies the substitutions defined in the dictionary to the formula.

    :param formula: The target formula
    :type  formula: FNode
    :param subs: Specify the substitutions to apply to the formula
    :type  subs: A dictionary from FNode to FNode
    :returns: Formula after applying the substitutions
    :rtype: Fnode
    """
    ...

def serialize(formula: FNode, threshold: Optional[int] = ...) -> str:
    """Provides a string representing the formula.

    :param formula: The target formula
    :type  formula: FNode
    :param threshold: Specify the threshold
    :type  formula: Integer
    :returns: A string representing the formula
    :rtype: string
    """
    ...

def get_free_variables(formula: FNode) -> frozenset[FNode]:
    """Returns the free variables of the formula.

    :param formula: The target formula
    :type  formula: FNode
    :returns: Free variables in the formula
    """
    ...

def get_atoms(formula: FNode) -> frozenset[FNode]:
    """Returns the set of atoms of the formula.

    :param formula: The target formula
    :type  formula: FNode
    :returns: the set of atoms of the formula
    """
    ...

def get_formula_size(formula: FNode, measure: Any = ...) -> int:
    """Returns the size of the formula as measured by the given counting type.

    See pysmt.oracles.SizeOracle for details.

    :param formula: The target formula
    :type  formula: FNode
    :param measure: Specify the measure/counting type
    :returns: The size of the formula as measured by the given counting type.
    """
    ...

def ForAll(variables: Collection[FNode], formula: FNode) -> FNode:
    r""".. math:: \forall v_1, \cdots, v_n . \varphi(v_1, \cdots, v_n)"""
    ...

def Exists(variables: Collection[FNode], formula: FNode) -> FNode:
    r""".. math:: \exists v_1, \cdots, v_n . \varphi(v_1, \cdots, v_n)"""
    ...

def Function(vname: FNode, params: list[FNode]) -> FNode:
    r""".. math:: vname(p_1, \cdots, p_n)"""
    ...

def Not(formula: FNode) -> FNode:
    r""".. math:: \lnot \varphi"""
    ...

def Implies(left: FNode, right: FNode) -> FNode:
    r""".. math:: l \rightarrow r"""
    ...

def Iff(left: FNode, right: FNode) -> FNode:
    r""".. math:: l \leftrightarrow r"""
    ...

def GE(left: FNode, right: FNode) -> FNode:
    r""".. math:: l \ge r"""
    ...

def Minus(left: FNode, right: FNode) -> FNode:
    r""".. math:: l - r"""
    ...

def Times(*args: FNode) -> FNode:
    r""".. math:: x_1 \times x_2 \cdots \times x_n"""
    ...

def Pow(left: FNode, right: FNode) -> FNode:
    r""".. math:: l ^ r"""
    ...

def Div(left: FNode, right: FNode) -> FNode:
    r""".. math:: \frac{l}{r}"""
    ...

def Equals(left: FNode, right: FNode) -> FNode:
    r""".. math:: l = r"""
    ...

def NotEquals(left: FNode, right: FNode) -> FNode:
    r""".. math:: l != r"""
    ...

def GT(left: FNode, right: FNode) -> FNode:
    r""".. math:: l > r"""
    ...

def LE(left: FNode, right: FNode) -> FNode:
    r""".. math:: l \le r"""
    ...

def LT(left: FNode, right: FNode) -> FNode:
    r""".. math:: l < r"""
    ...

def Ite(iff: FNode, left: FNode, right: FNode) -> FNode:
    r""".. math:: \text{ If } i \text{ Then } l \text{ Else } r"""
    ...

def Symbol(name: str, typename: PySMTType = ...) -> FNode:
    """Returns a symbol with the given name and type.

    :param name: Specify the name
    :param typename: Specify the typename
    :returns: A symbol with the given name and type
    """
    ...

def FreshSymbol(typename: PySMTType = ..., template: str = ...) -> FNode:
    """Returns a symbol with a fresh name and given type.

    :param typename: Specify the typename
    :param template: Specify the template
    :returns: A symbol with a fresh name and a given type
    """
    ...

def Int(value: int) -> FNode:
    """Returns an Integer constant with the given value.

    :param value: Specify the value
    :returns: An Integer constant with the given value
    """
    ...

def Bool(value: bool) -> FNode:
    """Returns a Boolean constant with the given value.

    :param value: Specify the value
    :returns: A Boolean constant with the given value
    """
    ...

def Real(value: Union[int, float, Fraction]) -> FNode:
    """Returns a Real constant with the given value.

    :param value: Specify the value
    :returns: A Real constant with the given value
    """
    ...

def String(value: str) -> FNode:
    """Returns a String constant with the given value."""
    ...

def TRUE() -> FNode:
    """Returns the Boolean constant TRUE.

    returns: The Boolean constant TRUE
    """
    ...

def FALSE() -> FNode:
    """Returns the Boolean constant FALSE.

    returns: The Boolean constant FALSE
    """
    ...

def And(*args: FNode) -> FNode:
    r""".. math:: \varphi_0 \land \cdots \land \varphi_n"""
    ...

def Or(*args: Union[FNode, Iterable[FNode]]) -> FNode:
    r""".. math:: \varphi_0 \lor \cdots \lor \varphi_n"""
    ...

def Plus(*args: Union[FNode, Iterable[FNode]]) -> FNode:
    r""".. math:: \varphi_0 + \cdots + \varphi_n"""
    ...

def ToReal(formula: FNode) -> FNode:
    """Explicit cast of a term into a Real term."""
    ...

def AtMostOne(*args: FNode) -> FNode:
    """At most one can be true at anytime.

    Cardinality constraint over a set of boolean expressions.
    """
    ...

def ExactlyOne(*args: FNode) -> FNode:
    """Given a set of boolean expressions requires that exactly one holds."""
    ...

def AllDifferent(*args: FNode) -> FNode:
    """Given a set of non-boolean expressions, requires that each of them
    has value different from all the others
    """
    ...

def Xor(left: FNode, right: FNode) -> FNode:
    """Returns the XOR of left and right

    :param left: Specify the left BV
    :type  left: FNode
    :param right: Specify the right BV
    :type  right: FNode
    :returns: The XOR of left and right
    """
    ...

def Min(*args: FNode) -> FNode:
    """Minimum over a set of real or integer terms."""
    ...

def Max(*args: FNode) -> FNode:
    """Maximum over a set of real or integer terms"""
    ...

def EqualsOrIff(left: FNode, right: FNode) -> FNode:
    """Returns Equals() or Iff() depending on the type of the arguments.

    This can be used to deal with ambiguous cases where we might be
    dealing with both Theory and Boolean atoms.
    """
    ...

def BV(value: Union[int, str], width: int = ...) -> FNode:
    """Returns a constant of type BitVector.

    value can be either:
    - a string of 0s and 1s
    - a string starting with "#b" followed by a sequence of 0s and 1s
    - an integer number s.t. 0 <= value < 2**width

    In order to create the BV representation of a signed integer,
    the SBV() method shall be used.

    :param value: Specify the value
    :param width: Specify the width
    :returns: A constant of type BitVector
    :rtype: FNode
    """
    ...

def SBV(value: Union[int, str], width: int = ...) -> FNode:
    """Returns a constant of type BitVector interpreting the sign.

    If the specified value is an integer, it is converted in the
    2-complement representation of the given number, otherwise the
    behavior is the same as BV().

    :param value: Specify the value
    :param width: Specify the width of the BV
    :returns: A constant of type BitVector interpreting the sign.
    :rtype: FNode
    """
    ...

def BVOne(width: int = ...) -> FNode:
    """Returns the unsigned one constant BitVector.

    :param width: Specify the width of the BitVector
    :returns: The unsigned one constant BitVector
    :rtype: FNode
    """
    ...

def BVZero(width: int = ...) -> FNode:
    """Returns the zero constant BitVector.

    :param width: Specify the width of the BitVector
    :returns: The unsigned zero constant BitVector
    :rtype: FNode
    """
    ...

def BVNot(formula: FNode) -> FNode:
    """Returns the bitwise negation of the bitvector

    :param formula: The target formula
    :returns: The bitvector Not(bv)
    :rtype: FNode
    """
    ...

def BVAnd(*args: FNode) -> FNode:
    """Returns the Bit-wise AND of bitvectors of the same size.
    If more than 2 arguments are passed, a left-associative formula is generated.

    :param *args: Specify the bitvectors
    :returns: The bit-wise AND of the bitvectors using left association
    :rtype: FNode
    """
    ...

def BVOr(*args: FNode) -> FNode:
    """Returns the Bit-wise OR of bitvectors of the same size.
    If more than 2 arguments are passed, a left-associative formula is generated.

    :param *args: Specify the bitvectors
    :returns: The bit-wise OR of the bitvectors using left association
    :rtype: FNode
    """
    ...

def BVXor(left: FNode, right: FNode) -> FNode:
    """Returns the Bit-wise XOR of two bitvectors of the same size.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The bit-wise XOR of left and right
    :rtype: FNode
    """
    ...

def BVConcat(*args: FNode) -> FNode:
    """Returns the Concatenation of the two BVs

    :param args: Specify the bitvectors to concatenate
    :returns: The concatenation of the given BVs
    :rtype: FNode
    """
    ...

def BVExtract(formula: FNode, start: int = ..., end: int = ...) -> FNode:
    """Returns the slice of formula from start to end (inclusive).

    :param formula: The target formula
    :param start: Specify the start index
    :param end: Specify the end index
    :returns: The slice of formula from start to end (inclusive)
    :rtype: Fnode
    """
    ...

def BVULT(left: FNode, right: FNode) -> FNode:
    """Returns the Unsigned Less-Than comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Unsigned Less-Than comparison of the two BVs
    :rtype: FNode
    """
    ...

def BVUGT(left: FNode, right: FNode) -> FNode:
    """Returns the Unsigned Greater-Than comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Unsigned Greater-Than comparison of the two BVs
    :rtype: FNode
    """
    ...

def BVULE(left: FNode, right: FNode) -> FNode:
    """Returns the Unsigned Less-Equal comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Unsigned Less-Equal comparison of the two BVs
    :rtype: FNode
    """
    ...

def BVUGE(left: FNode, right: FNode) -> FNode:
    """Returns the Unsigned Greater-Equal comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Unsigned Greater-Equal comparison of the two BVs
    :rtype: FNode
    """
    ...

def BVNeg(formula: FNode) -> FNode:
    """Returns the arithmetic negation of the BV.

    :param formula: The target formula
    :returns: The arithmetic negation of the formula
    :rtype: FNode
    """
    ...

def BVAdd(*args: FNode) -> FNode:
    """Returns the sum of BV.
    If more than 2 arguments are passed, a left-associative formula is generated.

    :param *args: Specify the bitvectors
    :returns: The sum of the bitvectors using left association.
    :rtype: FNode
    """
    ...

def BVSub(left: FNode, right: FNode) -> FNode:
    """Returns the difference of two BV.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The difference of the two BV
    :rtype: FNode
    """
    ...

def BVMul(*args: FNode) -> FNode:
    """Returns the product of BV.
    If more than 2 arguments are passed, a left-associative formula is generated.

    :param *args: Specify the bitvectors
    :returns: The product of the the bitvectors using left association
    :rtype: FNode
    """
    ...

def BVUDiv(left: FNode, right: FNode) -> FNode:
    """Returns the Unsigned division of the two BV.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Unsigned division of the two BV
    :rtype: FNode
    """
    ...

def BVURem(left: FNode, right: FNode) -> FNode:
    """Returns the Unsigned remainder of the two BV.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Unsigned remainder of the two BV
    :rtype: FNode
    """
    ...

def BVLShl(left: FNode, right: FNode) -> FNode:
    """Returns the logical left shift the BV.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The logical left shift the BV
    :rtype: FNode
    """
    ...

def BVLShr(left: FNode, right: FNode) -> FNode:
    """Returns the logical right shift the BV.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The logical right shift the BV
    :rtype: FNode
    """
    ...

def BVAShr(left: FNode, right: FNode) -> FNode:
    """Returns the RIGHT arithmetic shift of the left BV by the number
        of steps specified by the right BV.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The RIGHT arithmetic shift of the left BV by the number
              of steps specified by the right BV
    :rtype: FNode
    """
    ...

def BVRol(formula: FNode, steps: int) -> FNode:
    """Returns the LEFT rotation of the BV by the number of steps.

    :param formula: The target formula
    :param steps: Specify the number of steps.
    :returns: The LEFT rotation of the BV by the number of steps
    :rtype: FNode
    """
    ...

def BVRor(formula: FNode, steps: int) -> FNode:
    """Returns the RIGHT rotation of the BV by the number of steps.

    :param formula: The target formula
    :param steps: Specify the number of steps.
    :returns: The RIGHT rotation of the BV by the number of steps
    :rtype: FNode
    """
    ...

def BVZExt(formula: FNode, increase: int) -> FNode:
    """Returns the zero-extension of the BV.

    New bits are set to zero.

    :param formula: The target formula
    :param increase: Specify the increase
    :returns: The extension of the BV
    :rtype: FNode
    """
    ...

def BVSExt(formula: FNode, increase: int) -> FNode:
    """Returns the signed-extension of the BV.

    New bits are set according to the most-significant-bit.

    :param formula: The target formula
    :param increase: Specify the 'increase' value
    :returns: The signed-extension of the BV.
    :rtype: FNode
    """
    ...

def BVSLT(left: FNode, right: FNode) -> FNode:
    """Returns the Signed Less-Than comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Signed Less-Than comparison of the two BVs
    :rtype: FNode
    """
    ...

def BVSLE(left: FNode, right: FNode) -> FNode:
    """Returns the Signed Less-Equal comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Signed Less-Than-Equal comparison of the two BVs
    :rtype: FNode
    """
    ...

def BVSGT(left: FNode, right: FNode) -> FNode:
    """Returns the Signed Greater-Than comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Signed Greater-Than comparison of the two BVs
    :rtype: FNode
    """
    ...

def BVSGE(left: FNode, right: FNode) -> FNode:
    """Returns the Signed Greater-Equal comparison of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Signed Greater-Equal comparison of the two BVs.
    :rtype: FNode
    """
    ...

def BVSDiv(left: FNode, right: FNode) -> FNode:
    """Returns the Signed division of the two BVs.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The the Signed division of left by right
    :rtype: FNode
    """
    ...

def BVSRem(left: FNode, right: FNode) -> FNode:
    """Returns the Signed remainder of the two BVs

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: The Signed remainder of left divided by right
    :rtype: FNode
    """
    ...

def BVComp(left: FNode, right: FNode) -> FNode:
    """Returns a BV of size 1 equal to 0 if left is equal to right,
        otherwise equal to 1.

    :param left: Specify the left bitvector
    :param right: Specify the right bitvector
    :returns: A BV of size 1 equal to 0 if left is equal to right,
              otherwise 1
    :rtype: FNode
    """
    ...

def BVToNatural(formula: FNode) -> FNode:
    """Returns the Natural number represented by the BitVector.

    :param formula: Bitvector to be converted
    :returns: An integer between 0 and 2^m-1
    :rtype: FNode
    """
    ...

def StrLength(string: FNode) -> FNode:
    """Returns the length of a formula resulting a String"""
    ...

def StrCharAt(string: FNode, index: FNode) -> FNode:
    """Returns a single character String at position i.

    s is a string term and i is an integer term. i is the position.
    """
    ...

def StrConcat(*args: FNode) -> FNode:
    """Returns the concatenation of n Strings.

    s1, s2, ..., and sn are String terms.
    String concatenation takes at least 2 arguments.
    """
    ...

def StrContains(string: FNode, target: FNode) -> FNode:
    """Returns wether string contains the target.

    s and t are String terms.
    """
    ...

def StrIndexOf(string: FNode, target: FNode, offset: FNode) -> FNode:
    """Returns the position of the first occurrence of target in string after the offset.

    s and t being a non empty strings and i a non-negative integer.
    It returns -1 if the value to search for never occurs.
    """
    ...

def StrReplace(s: FNode, t1: FNode, t2: FNode) -> FNode:
    """Returns a new string where the first occurrence of t1 is replace by t2.

    where s, t1 and t2 are string terms, t1 is non-empty.
    """
    ...

def StrSubstr(s: FNode, i: FNode, j: FNode) -> FNode:
    """Returns a substring of s starting at i and ending at j+i.

    where s is a string term and i, j are integer terms.
    """
    ...

def StrPrefixOf(s: FNode, t: FNode) -> FNode:
    """Returns whether the s is a prefix of the string t.

    where s and t are string terms.
    """
    ...

def StrSuffixOf(s: FNode, t: FNode) -> FNode:
    """Returns whether the string s is a suffix of the string t.

    where s and t are string terms.
    """
    ...

def StrToInt(x: FNode) -> FNode:
    """Returns the corresponding natural number of s is valid;

    If s is not valid, it returns -1.
    """
    ...

def IntToStr(x: FNode) -> FNode:
    """Returns the corresponding String representing the natural number x.

    where x is an integer term. If x is not a natural number it
    returns the empty String.
    """
    ...

def Select(array: FNode, index: FNode) -> FNode:
    """Returns a SELECT application on the array at the given index

    :param array: Specify the array
    :param index: Specify the index
    :returns: A SELECT application on array at index
    :rtype: FNode
    """
    ...

def Store(array: FNode, index: FNode, value: FNode) -> FNode:
    """Returns a STORE application with given value on array at the given index

    :param array: Specify the array
    :param index: Specify the index
    :returns: A STORE on the array at the given index with the given value
    :rtype: FNode
    """
    ...

def Array(idx_type: PySMTType, default: FNode, assigned_values: dict[FNode, FNode] = ...) -> FNode:
    """Returns an Array with the given index type and initialization.

    If assigned_values is specified, then it must be a map from
    constants of type idx_type to values of the same type as default
    and the array is initialized correspondingly.

    :param idx_type: Specify the index type
    :param default: Specify the default values
    :param assigned_values: Specify the assigned values
    :returns: A node representing an array having index type equal to
              idx_type, initialized with default values. If assigned_values
              is specified, then it must be a map from constants of type
              idx_type to values of the same type as default and the array
              is initialized correspondingly.
    :rtype: FNode
    """
    ...

def Solver(name: str = ..., logic: Any = ..., **kwargs: Any) -> Any:
    """Returns a solver.

    :param name: Specify the name of the solver
    :param logic: Specify the logic that is going to be used.
    :rtype: Solver
    """
    ...

def UnsatCoreSolver(name: str = ..., logic: Any = ..., unsat_cores_mode: Any = ..., **kwargs: Any) -> Any:
    """Returns a solver supporting unsat core extraction.

    :param name: Specify the name of the solver
    :param logic: Specify the logic that is going to be used.
    :param unsat_cores_mode: Specify the unsat cores mode.
    :returns: A solver supporting unsat core extraction.
    :rtype: Solver
    """
    ...

def QuantifierEliminator(name: str = ..., logic: Any = ...) -> Any:
    """Returns a quantifier eliminator.

    :param name: Specify the name of the solver
    :param logic: Specify the logic that is going to be used.
    :returns: A quantifier eliminator with the specified
              name and logic
    :rtype: QuantifierEliminator
    """
    ...

def Interpolator(name: str = ..., logic: Any = ...) -> Any:
    """Returns an interpolator

    :param name: Specify the name of the solver
    :param logic: Specify the logic that is going to be used.
    :returns: An interpolator
    :rtype: Interpolator
    """
    ...

def Portfolio(solvers_set: Any, logic: Any, **options: Any) -> Any:
    """Creates a portfolio using the specified solvers.

    Solver_set is an iterable. Elements of solver_set can be
      1) a name of a solver
      2) a tuple containing a name of a solver and dict of options

    E.g.,
      Portfolio(["msat", "z3"], incremental=True)
    or
      Portfolio([("msat", {"random_seed": 1}), ("msat", {"random_seed": 2})],
               incremental=True)

    Options specified in the Portfolio are shared among all
    solvers, e.g., in the first example all solvers will receive
    the option 'incremental=True'.

    One process will be used for each of the solvers.

    :param solvers_set: Specify set of solvers to be used in the portfolio.
    :param logic: Specify the logic that is going to be used, this
        might restrict the set of solvers in the portfolio.
    :returns: A portfolio solver
    :rtype: Portfolio
    """
    ...

def is_sat(formula: FNode, solver_name: str = ..., logic: Any = ..., portfolio: Any = ...) -> bool:
    """Returns whether a formula is satisfiable.

    :param formula: The formula to check satisfiability
    :type  formula: FNode
    :param solver_name: Specify the name of the solver to be used
    :type  solver_name: string
    :param logic: Specify the logic that is going to be used
    :param portfolio: A list of solver names to perform portfolio solving.
    :type  portfolio: An iterable of solver names
    :returns: Whether the formula is SAT or UNSAT.
    :rtype: bool
    """
    ...

def get_model(formula: FNode, solver_name: str = ..., logic: Any = ...) -> Optional[Any]:
    """Similar to :py:func:`is_sat` but returns a model if the formula is
    satisfiable, otherwise None

    :param formula: The target formula
    :param solver_name: Specify the name of the solver
    :param: logic: Specify the logic that is going to be used
    :returns: A model if the formula is satisfiable
    :rtype: Model
    """
    ...

def get_implicant(formula: FNode, solver_name: str = ..., logic: Any = ...) -> Optional[FNode]:
    """Returns a formula f_i such that Implies(f_i, formula) is valid or None
    if formula is unsatisfiable.

    if complete is set to true, all the variables appearing in the
    formula are forced to appear in f_i.
    :param formula: The target formula
    :param solver_name: Specify the name of the solver
    :param: logic: Specify the logic that is going to be used
    :returns: A formula f_i such that Implies(f_i, formula) is valid or None
              if formula is unsatisfiable.
    :rtype: FNode
    """
    ...

def get_unsat_core(clauses: Iterable[FNode], solver_name: str = ..., logic: Any = ...) -> list[FNode]:
    """Similar to :py:func:`get_model` but returns the unsat core of the
    conjunction of the input clauses

    :param clauses: Specify the list of input clauses
    :param solver_name: Specify the name of the solver_name
    :param logic: Specify the logic that is going to be used
    :returns: The unsat core of the conjunction of the input clauses
    """
    ...

def is_valid(formula: FNode, solver_name: str = ..., logic: Any = ..., portfolio: Any = ...) -> bool:
    """Similar to :py:func:`is_sat` but checks validity.

    :param formula: The target formula
    :type  formula: FNode
    :param solver_name: Specify the name of the solver to be used
    :param logic: Specify the logic that is going to be used
    :param portfolio: A list of solver names to perform portfolio solving.
    :returns: Whether the formula is SAT or UNSAT but checks validity
    :rtype: bool
    """
    ...

def is_unsat(formula: FNode, solver_name: str = ..., logic: Any = ..., portfolio: Any = ...) -> bool:
    """Similar to :py:func:`is_sat` but checks unsatisfiability.

    :param formula: The target formula
    :type  formula: FNode
    :param solver_name: Specify the name of the solver to be used
    :param logic: Specify the logic that is going to be used
    :param portfolio: A list of solver names to perform portfolio solving.
    :returns: Whether the formula is UNSAT or not
    :rtype: bool
    """
    ...

def qelim(formula: FNode, solver_name: str = ..., logic: Any = ...) -> FNode:
    """Performs quantifier elimination of the given formula.

    :param formula: The target formula
    :param solver_name: Specify the name of the solver to be used
    :param logic: Specify the logic that is going to be used
    :returns: A formula after performing quantifier elimination
    :rtype: FNode
    """
    ...

def binary_interpolant(formula_a: FNode, formula_b: FNode, solver_name: str = ..., logic: Any = ...) -> Optional[FNode]:
    """Computes an interpolant of (formula_a, formula_b).

    Returns None if the conjunction is satisfiable

    :param formula_a: Specify formula_a
    :param formula_b: Specify formula_b
    :param solver_name: Specify the name of the solver to be used
    :param logic: Specify the logic that is going to be used
    :returns: An interpolant of (formula_a, formula_b); None
              if the conjunction is satisfiable
    :rtype: FNode or None
    """
    ...

def sequence_interpolant(formulas: Iterable[FNode], solver_name: str = ..., logic: Any = ...) -> Optional[list[FNode]]:
    """Computes a sequence interpolant of the formulas.

    Returns None if the conjunction is satisfiable.

    :param formulas: The target formulas
    :param solver_name: Specify the name of the solver to be used
    :param logic: Specify the logic that is going to be used
    :returns: A sequence intepolant of the formulas; None
              if the conjunction is satisfiable
    :rtype: FNode or None
    """
    ...

def read_configuration(config_filename: str, environment: Environment = ...) -> None:
    """Reads the pysmt configuration of the given file path and applies
    it on the specified environment. If no environment is specified,
    the top-level environment will be used.

    :param config_filename: Specify the name of the config file
    :param environment: Specify the environment
    """
    ...

def write_configuration(config_filename: str, environment: Environment = ...) -> None:
    """Dumps the current pysmt configuration to the specified file path

    :param config_filename: Specify the name of the config file
    :param environment: Specify the environment
    """
    ...

def read_smtlib(fname: str) -> FNode:
    """Reads the SMT formula from the given file.

    This supports compressed files, if the fname ends in .bz2 .

    :param fname: Specify the filename
    :returns: An SMT formula
    :rtype: FNode
    """
    ...

def write_smtlib(formula: FNode, fname: str) -> None:
    """Writes the given formula in Smt-Lib format to the given file.

    :param formula: Specify the SMT formula to be written
    :param fname: Specify the filename
    """
    ...

def to_smtlib(formula: FNode, daggify: bool = ...) -> str:
    """Returns a Smt-Lib string representation of the formula.

    The daggify parameter can be used to switch from a linear-size
    representation that uses 'let' operators to represent the
    formula as a dag or a simpler (but possibly exponential)
    representation that expands the formula as a tree.

    See :py:class:`SmtPrinter`
    """
    ...
