"""
This type stub file was generated by pyright.
"""

import pysmt.operators as op
import pysmt.walkers
from pysmt.walkers.generic import handles

class FunctionInterpretation:
    """This class represents the interpretation of an uninterpreted
    function symbol and is intended to be used in substitutions.

    For example, let `phi` be the formula `phi = Equals(Function(f,
    [Int(2), Int(3)]), a)` where `a` is a Symbol of type INT and `f`
    is an uninterpreted function with two INT parameters that returns
    INT. A possible interpretation for `f` could be `f(x, y) = x + y`
    and a model for `a` could be `5`.

    To represent a model in pysmt we simply use a dict from symbols to
    constant values, but for interpretations we need a map from
    symbols to instances of FunctionInterpretation. Each instance of
    FunctionInterpretation represents the interpretation of a
    function.

    A FunctionInterpretation is represented as a list of symbols, each
    having the type corresponding to the parameter types of the
    function to be interpreted, plus a function body that is an
    expression that can only depend on the formal parameters. So to
    represent the interpretation `f(x, y) = x + y` we construct the
    instance as follows:

    ```
    x, y = Symbol('x', INT), Symbol('y', INT)
    FunctionInterpretation([x, y], Plus(x, y))
    ```
    """
    def __init__(self, formal_params, function_body, allow_free_vars=...) -> None:
        """Constructor, taking in input the list of formal parameters and the
        function body.

        The parameter `allow_free_vars` is used to skip the check that
        the function body has no free variables other than formal
        parameter and is used in the SmtLib model-validation utility
        because functions with uninterpreted return value return
        special symbols (e.g. @val1) in SmtLib.
        """
        ...

    def interpret(self, env, actual_params):  # -> Any:
        """Given a set of actual parameter, returns the 'value' of the
        function by substituting formal parameters with their actual
        values.
        """
        ...

class Substituter(pysmt.walkers.IdentityDagWalker):
    """Performs substitution of a set of terms within a formula.

    Let f be a formula ans subs be a map from formula to formula.
    Substitution returns a formula f' in which all occurrences of the
    keys of the map have been replaced by their value.

    There are a few considerations to take into account:
      - In which order to apply the substitution
      - How to deal with quantified subformulas

    The order in which we apply the substitutions gives raise to two
    different approaches: Most General Substitution and Most Specific
    Substitution. Lets consider the example:

      f = (a & b)
      subs = {a -> c, (c & b) -> d, (a & b) -> c}

    With the Most General Substitution (MGS) we obtain:
      f' = c
    with the Most Specific Substitution (MSS) we obtain:
      f' = d

    The default behavior before version 0.5 was MSS. However, this
    leads to unexpected results when dealing with literals, i.e.,
    substitutions in which both x and Not(x) appear, do not work as
    expected.  In case of doubt, it is recommended to issue two
    separate calls to the substitution procedure.
    """
    def __init__(self, env) -> None: ...
    def substitute(self, formula, subs=..., interpretations=...):
        """Replaces any subformula in formula with the definition in subs (if
        any) and interprets function symbols with the interpretations
        in `interpretations`

        For example, let `phi` be the formula `phi = Equals(Function(f,
        [Int(2), Int(3)]), Plus(a, Int(1)))` where `a` is a Symbol of type INT and `f`
        is an uninterpreted function with two INT parameters that returns
        INT.

        Examples:

        - Basic substitution:
        `self.substitute(phi, {a: Int(5)})`
        will give `Equals(Function(f, [Int(2), Int(3)]), Plus(Int(5), Int(1)))`

        - Interpretation:
        ```
        x, y = Symbol('x', INT), Symbol('y', INT)
        i = FunctionInterpretation([x, y], Plus(x, y))
        self.substitute(phi, interpretations={f:i})
        ```
        will give `Equals(Int(5), Plus(a, Int(1)))`

        - Term substitution
        `self.substitute(phi, {Plus(a, Int(1)): Int(5)})`
        will give `Equals(Function(f, [Int(2), Int(3)]), Int(6))`
        """
        ...

    def walk_function(self, formula, args, **kwargs):  # -> Any:
        ...

class MGSubstituter(Substituter):
    """Performs Most Generic Substitution.

    This is the default behavior since version 0.5
    """
    def __init__(self, env) -> None: ...
    @handles(set(op.ALL_TYPES) - op.QUANTIFIERS - op.FUNCTION)
    def walk_identity_or_replace(self, formula, args, **kwargs):  # -> Any:
        """
        If the formula appears in the substitution, return the substitution.
        Otherwise, rebuild the formula by calling the IdentityWalker.
        """
        ...

    def walk_forall(self, formula, args, **kwargs): ...
    def walk_exists(self, formula, args, **kwargs): ...

class MSSubstituter(Substituter):
    """Performs Most Specific Substitution.

    This was the default behavior before version 0.5
    """
    def __init__(self, env) -> None: ...
    def substitute(self, formula, subs): ...
    @handles(set(op.ALL_TYPES) - op.QUANTIFIERS - op.FUNCTION)
    def walk_replace(self, formula, args, **kwargs): ...
    def walk_forall(self, formula, args, **kwargs): ...
    def walk_exists(self, formula, args, **kwargs): ...
