"""
This type stub file was generated by pyright.
"""

"""This module defines the types of the formulae handled by pySMT.

In the current version these are:
 * Bool
 * Int
 * Real
 * BVType
 * FunctionType
 * ArrayType

Types are represented by singletons. Basic types (Bool, Int and Real)
are constructed here by default, while BVType and FunctionType relies
on a factory service. Each BitVector width is represented by a
different instance of BVType.

"""

class PySMTType:
    """Class for representing a type within pySMT.

    Instances of this class are used to represent sorts.
    The subclass FunctionType is used to represent function declarations.

    """
    def __init__(self, decl=..., basename=..., args=...) -> None: ...
    def is_bool_type(self):  # -> Literal[False]:
        ...
    def is_real_type(self):  # -> Literal[False]:
        ...
    def is_int_type(self):  # -> Literal[False]:
        ...
    def is_bv_type(self, width=...):  # -> Literal[False]:
        ...
    def is_array_type(self):  # -> Literal[False]:
        ...
    def is_string_type(self):  # -> Literal[False]:
        ...
    def is_function_type(self):  # -> Literal[False]:
        ...
    def is_custom_type(self):  # -> bool:
        ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __repr__(self):  # -> str:
        ...
    def as_smtlib(self, funstyle=...):  # -> str | None:
        ...
    def __str__(self) -> str: ...

class _BoolType(PySMTType):
    def __init__(self) -> None: ...
    def is_bool_type(self):  # -> Literal[True]:
        ...

class _IntType(PySMTType):
    def __init__(self) -> None: ...
    def is_int_type(self):  # -> Literal[True]:
        ...

class _RealType(PySMTType):
    def __init__(self) -> None: ...
    def is_real_type(self):  # -> Literal[True]:
        ...

class _StringType(PySMTType):
    def __init__(self) -> None: ...
    def is_string_type(self):  # -> Literal[True]:
        ...

class _ArrayType(PySMTType):
    """Internal class used to represent an Array type.

    This class should not be instantiated directly, but the factory
    method ArrayType should be used instead.
    """

    _instances = ...
    def __init__(self, index_type, elem_type) -> None: ...
    @property
    def elem_type(self):
        """Returns the element type.

        E.g.,  A: (Array Int Real)
        Returns RealType.
        """
        ...

    @property
    def index_type(self):
        """Returns the index type.

        E.g.,  A: (Array Int Real)
        Returns IntType.
        """
        ...

    def is_array_type(self):  # -> Literal[True]:
        ...

class _BVType(PySMTType):
    """Internal class to represent a BitVector type.

    This class should not be instantiated directly, but the factory
    method BVType should be used instead.
    """

    _instances = ...
    def __init__(self, width=...) -> None: ...
    @property
    def width(self):  # -> int:
        ...
    def is_bv_type(self, width=...):  # -> Literal[True]:
        ...
    def as_smtlib(self, funstyle=...):  # -> str:
        ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

class _FunctionType(PySMTType):
    """Internal class used to represent a Function type.

    This class should not be instantiated directly, but the factory
    method FunctionType should be used instead.
    """

    _instances = ...
    def __init__(self, return_type, param_types) -> None: ...
    @property
    def param_types(self):  # -> tuple[Any, ...]:
        """Returns the arguments of the Function Type.

        E.g.,  F: (Bool -> Bool) -> Real
        Returns [BoolType, BoolType].
        """
        ...

    @property
    def return_type(self):  # -> Any:
        """Returns the return type of  the Function Type.

        E.g.,  F: (Bool -> Bool) -> Real
        Returns RealType.
        """
        ...

    def as_smtlib(self, funstyle=...):  # -> LiteralString:
        ...
    def __str__(self) -> str: ...
    def is_function_type(self):  # -> Literal[True]:
        ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

class _TypeDecl:
    """Create a new Type Declaration (sort).

    This is equivalent to the SMT-LIB command "declare-sort".
    NOTE: This object is **not** a Type, but a Type Declaration.
    """
    def __init__(self, name, arity) -> None: ...
    def __call__(self, *args): ...
    def __str__(self) -> str: ...
    def set_custom_type_flag(self):  # -> None:
        ...

class PartialType:
    """PartialType allows to delay the definition of a Type.

    A partial type is equivalent to SMT-LIB "define-sort" command.
    """
    def __init__(self, name, definition) -> None: ...
    def __str__(self) -> str: ...
    def __call__(self, *args): ...

BOOL = ...
REAL: PySMTType = ...
INT: PySMTType = ...
STRING = ...
PYSMT_TYPES = ...
ARRAY_INT_INT = ...

class TypeManager:
    def __init__(self, environment) -> None: ...
    def load_global_types(self):  # -> None:
        """Register basic global types within the TypeManager."""
        ...

    def BOOL(self):  # -> _BoolType | None:
        ...
    def REAL(self):  # -> _RealType | None:
        ...
    def INT(self):  # -> _IntType | None:
        ...
    def STRING(self):  # -> _StringType | None:
        ...
    def BVType(self, width=...):  # -> _BVType:
        """Returns the singleton associated to the BV type for the given width.

        This function takes care of building and registering the type
        whenever needed. To see the functions provided by the type look at
        _BVType.
        """
        ...

    def FunctionType(self, return_type, param_types):  # -> _FunctionType:
        """Returns the singleton of the Function type with the given arguments.

        This function takes care of building and registering the type
        whenever needed. To see the functions provided by the type look at
        _FunctionType

        Note: If the list of parameters is empty, the function is
        equivalent to the return type.
        """
        ...

    def ArrayType(self, index_type, elem_type):  # -> _ArrayType:
        """Returns the singleton of the Array type with the given arguments.

        This function takes care of building and registering the type
        whenever needed. To see the functions provided by the type look at
        _ArrayType
        """
        ...

    def Type(self, name, arity=...):  # -> PySMTType | _TypeDecl:
        """Creates a new Type Declaration (sort declaration).

        This is equivalent to the SMT-LIB command "declare-sort".  For
        sorts of arity 0, we return a PySMTType, all other sorts need to
        be instantiated.

        See class _Type.
        """
        ...

    def get_type_instance(self, type_decl, *args):  # -> PySMTType:
        """Creates an instance of the TypeDecl with the given arguments."""
        ...

    def normalize(self, type_):
        """Recursively recreate the given type within the manager.

        This proceeds iteratively on the structure of the type tree.
        """
        ...

def assert_is_type(target, func_name):  # -> None:
    ...
def assert_are_types(targets, func_name):  # -> None:
    ...
def BVType(width=...):
    """Returns the BV type for the given width."""
    ...

def FunctionType(return_type, param_types):
    """Returns Function Type with the given arguments."""
    ...

def ArrayType(index_type, elem_type):
    """Returns the Array type with the given arguments."""
    ...

def Type(name, arity=...):
    """Returns the Type Declaration with the given name (sort declaration)."""
    ...
