"""
This type stub file was generated by pyright.
"""

def all_assignments(bool_variables, env):  # -> Generator[dict[Any, Any], Any, None]:
    """Generates all possible assignments for a set of boolean variables."""
    ...

def powerset(elements):  # -> chain[tuple[Any, ...]]:
    """Generates the powerset of the given elements set.

    E.g., powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)
    """
    ...

def set_bit(v, index, x):
    """Set the index:th bit of v to x, and return the new value."""
    ...

def twos_complement(val, bits):
    """Retuns the 2-complemented value of val assuming bits word width"""
    ...

def interactive_char_iterator(handle):  # -> Generator[Any, Any, None]:
    ...

_simple_symbol_prog = ...
_keywords = ...

def quote(name, style=...):  # -> str:
    ...
