"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

from pychc.solvers import proof_checker
from pychc.solvers.smt_solver import SMTSolver
from pychc.solvers.witness import SatWitness, UnsatWitness, Witness
from pysmt.fnode import FNode
from pysmt.logics import Logic

class CHCSystem:
    def __init__(self, logic: Logic) -> None: ...
    @classmethod
    def load_from_file(cls, path: Path, logic: Optional[Logic] = ...) -> CHCSystem:
        """Load a CHC system from an SMT-LIB file."""
        ...

    def invalidate_data(self) -> None: ...
    def get_logic(self) -> Optional[Logic]: ...
    def add_predicate(self, pred: FNode) -> None:
        """
        Register a predicate symbol with its signature.

        :param pred: a pysmt Symbol of type FunctionType
        """
        ...

    def get_predicates(self) -> set[FNode]: ...
    def add_clauses(self, clauses: set[FNode]) -> None: ...
    def add_clause(self, clause: FNode) -> int:
        """
        Add a CHC clause.

        :param clause: a pysmt FNode representing a CHC clause.
        It must have no free variables and use a compliant logic.
        """
        ...

    def remove_clause(self, clause_idx: int) -> None: ...
    def get_clauses(self) -> list[FNode]: ...
    def check_witness_consistency(self, witness: Witness) -> bool:
        """
        Check whether the given witness is *syntactically* consistent with the system.

        :param witness: a Witness containing the interpretations for the predicates

        """
        ...

    def validate_sat_model(
        self, witness: SatWitness, smt_validator: SMTSolver, timeout: Optional[int] = ...
    ):  # -> None:
        ...
    def validate_unsat_proof(
        self, witness: UnsatWitness, proof_checker: proof_checker.ProofChecker, timeout: Optional[int] = ...
    ):  # -> None:
        ...
    def strengthen_clause_with_witness(self, clause_id: int, witness: SatWitness) -> int:
        """
        Learn new clauses from the given witness.

        :param witness: a Witness containing the interpretations for the predicates
        """
        ...

    def get_smt2file(self) -> Path: ...
    def serialize(self, out_path: Path) -> Path:
        """
        Serialize the system to SMT-LIB at `out_path`.

        Emits:
        - `(set-logic HORN)`
        - `(declare-fun <pred> (<arg_sorts> ) <return_sort>)` for each predicate
        - `(assert <clause>)` for each clause
        - `(check-sat)` at the end

        :return: the Path where the system was written
        """
        ...
