"""
This type stub file was generated by pyright.
"""

from pychc.operators import FormulaManager
from pysmt.environment import Environment as PysmtEnvironment

class Environment(PysmtEnvironment):
    """Extension of pySMT environment for pyCHC to support `mod`."""

    FormulaManagerClass = FormulaManager

def push_env(env=...):  # -> None:
    """Overload push_env to default to pyCHC Environment."""
    ...

def reset_env(): ...
