"""
This type stub file was generated by pyright.
"""

import pysmt.formula
from pysmt.fnode import FNode

MOD = ...
INTDIV = ...

class FormulaManager(pysmt.formula.FormulaManager):
    """Extend PySMT FormulaManager with integer `mod` operator."""
    def Mod(self, left: FNode, right: FNode) -> FNode: ...
    def IntDiv(self, left: FNode, right: FNode) -> FNode: ...
