"""
This type stub file was generated by pyright.
"""

from pathlib import Path

from pychc.solvers.witness import Status
from pysmt.smtlib.parser import SmtLibParser

class CHCSmtLibParser(SmtLibParser):
    """Custom SMT-LIB parser with LIA symbols."""
    def __init__(self, *args, **kwargs) -> None: ...

def scan_commands_in_smtlib_file(file: Path) -> list[str]:
    """
    Split an SMT-LIB file into command strings.
    """
    ...

def scan_commands(text: str) -> list[str]: ...
def decide_result(text: str) -> tuple[Status, str]:
    """
    Decide the solving result (SAT/UNSAT/UNKNOWN) from first line.
    Returns the status and the remaining output.
    If first line is not sat/unsat/unknown, raises PyCHCUnknownResultException.
    """
    ...
