"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

from pysmt.fnode import FNode
from pysmt.typing import PySMTType

def Predicate(name: str, arg_types: list[PySMTType]) -> FNode:
    """
    A predicate is a function symbol returning Bool with the given argument types.
    """
    ...

def Apply(pred: FNode, args: list[FNode]) -> FNode:
    """
    Apply a predicate predicate name to a list of arguments.

    :param pred: a pysmt FNode representing a predicate (i.e., a function symbol
                 with Boolean return type)
    :param args: a list of pysmt FNode representing the arguments
    :return: a pysmt FNode representing the application of the predicate to the arguments
    """
    ...

def Clause(body: Optional[FNode] = ..., head: FNode = ...) -> FNode:
    """
    Create a CHC clause from a head and an optional body.

    :param head: a pysmt FNode representing the head of the clause
    :param body: a pysmt FNode representing the body of the clause (optional)
     if not provided, the body is assumed to be TRUE
    :return: a pysmt FNode representing the CHC clause
    """
    ...

def Mod(left: FNode, right: FNode) -> FNode:
    """
    Integer modulus operator shortcut.
    """
    ...

def IntDiv(left: FNode, right: FNode) -> FNode:
    """
    Integer division operator shortcut (SMT-LIB: div).
    """
    ...

class SMTLibFormula(FNode):
    @classmethod
    def load_from_file(cls, file_path: Path) -> FNode:
        """
        Load a formula from an SMT-LIBv2 file.

        :param file_path: path to the SMT-LIBv2 file
        :return: the asserted formula in the file
        """
        ...
