"""
This type stub file was generated by pyright.
"""

from pysmt.solvers.solver import Model

class EagerModel(Model):
    """A model that does not require the existence of a solver instance.

    This is useful when we want to change the state of the solver but
    maintain a version of the previously found model. An EagerModel
    can also be constructed manually, and provides a simple way to
    define a model.
    """
    def __init__(self, assignment, environment=...) -> None: ...
    def get_value(self, formula, model_completion=...): ...
    def iterator_over(self, language):  # -> Generator[tuple[Any, Any], Any, None]:
        ...
    def __iter__(self):  # -> Iterator[tuple[Any, Any]]:
        """Overloading of iterator from Model.  We iterate only on the
        variables defined in the assignment.
        """
        ...

    def __contains__(self, x):  # -> bool:
        """Returns whether the model contains a value for 'x'."""
        ...
