"""
This type stub file was generated by pyright.
"""

class Interpolator:
    def __init__(self) -> None: ...
    def binary_interpolant(self, a, b):
        """Returns a binary interpolant for the pair (a, b), if And(a, b) is
        unsatisfiable, or None if And(a, b) is satisfiable.

        """
        ...

    def sequence_interpolant(self, formulas):
        """Returns a sequence interpolant for the conjunction of formulas, or
        None if the problem is satisfiable.

        """
        ...

    def __enter__(self):  # -> Self:
        """Manage entering a Context (i.e., with statement)"""
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        """Manage exiting from Context (i.e., with statement)

        The default behaviour is to explicitly destroy the interpolator to
        free the associated resources.

        """
        ...

    def exit(self):  # -> None:
        """Destroys the solver and closes associated resources."""
        ...
