"""
This type stub file was generated by pyright.
"""

import abc

"""A SolverOptions class is associated to each Solver to handle its
configuration. We consider two types of options. The first type is
available in most solvers, while the second type is solver-specific.

The first type is handled and documented in the base class
SolverOptions: generate_models, incremental etc.
The second type is handled within the dictionary "solver_options".

To use the Options it is necessary to:

* Define the class attribute OptionsClass within the Solver Class
* Validate the options during in SolverOptions.__init__
* Implement the method SolverOptions.__call__
* During Solver.__init__ the solver must call the option class::

    self.options(self)

"""

class SolverOptions:
    """Solver Options shared by most solvers.

    * generate_models : True, False
      Enable model generation. Needed for get_value, get_model etc.

    * incremental: True, False
      Enable incremental interface (push, pop)

    * unsat_cores_mode: None, "named", "all"
      Enable UNSAT core extraction using "named" or "all" strategy.

    * random_seed: None, integer
      Sets the random seed for the solver

    * solver_options: dictionary
      Provides solver specific options

    """

    __metaclass__ = abc.ABCMeta
    def __init__(
        self, generate_models=..., incremental=..., unsat_cores_mode=..., random_seed=..., solver_options=...
    ) -> None: ...
    @abc.abstractmethod
    def __call__(self, solver):
        """Handle the setting options within solver"""
        ...

    def as_kwargs(self):  # -> dict[Any, Any]:
        """Construct a dictionary object that can be used as **kwargs.

        This can be used to duplicate the options.
        """
        ...
