"""
This type stub file was generated by pyright.
"""

from pysmt.decorators import catch_conversion_error, clear_pending_pop
from pysmt.solvers.solver import Solver, SolverOptions

class PicosatOptions(SolverOptions):
    """Options for Picosat Solver.

    * preprocessing: True, False
      Enable pre-processing

    * enable_trace_generation: True, False
      Enable trace generations (needed for UNSAT-cores)

    * output: None, Filename
      Define where to print output (default: None = stdout)

    * global_default_phase: None, ALL_GLOBAL_DEFAULT_PHASE
      Default phase for new decision literals.

    * more_important_lit: None, list of Symbols
      Increase the priority of the literals on which to make decisions

    * less_important_lit: None, list of Symbols
      Decrease the priority of the literals on which to make decisions

    * propagation_limit: None, long
      Limit the search to at most this many propagations.

    * verbosity: Integer
      Verbosity level. Set to 1 if output is defined.
    """

    ALL_GLOBAL_DEFAULT_PHASE = ...
    def __init__(self, **base_options) -> None: ...
    def __call__(self, solver):  # -> None:
        """Handle Options"""
        ...

class PicosatSolver(Solver):
    """PicoSAT solver"""

    LOGICS = ...
    OptionsClass = PicosatOptions
    def __init__(self, environment, logic, **options) -> None: ...
    @clear_pending_pop
    def reset_assertions(self):  # -> None:
        ...
    @clear_pending_pop
    def declare_variable(self, var): ...
    @clear_pending_pop
    @catch_conversion_error
    def add_assertion(self, formula, named=...):  # -> None:
        ...
    @clear_pending_pop
    @catch_conversion_error
    def solve(self, assumptions=...):  # -> bool:
        ...
    def get_value(self, item): ...
    def get_model(self):  # -> EagerModel:
        ...
    @clear_pending_pop
    def push(self, levels=...):  # -> None:
        ...
    @clear_pending_pop
    def pop(self, levels=...):  # -> None:
        ...
