"""
This type stub file was generated by pyright.
"""

from pysmt.solvers.solver import IncrementalTrackingSolver, SolverOptions

LOGGER = ...
_debug = ...

class PortfolioOptions(SolverOptions):
    def __init__(self, **base_options) -> None: ...
    def __call__(self, solver):  # -> None:
        ...

class Portfolio(IncrementalTrackingSolver):
    """Create a portfolio instance of multiple Solvers."""

    OptionsClass = PortfolioOptions
    def __init__(self, solvers_set, environment, logic, **options) -> None:
        """Creates a portfolio using the specified solvers.

        Solver_set is an iterable. Elements of solver_set can be
         1) a name of a solver
         2) a tuple containing a name of a solver and dict of options

        E.g.,
           Portfolio(["msat", "z3"], incremental=True)
              or
           Porfolio([("msat", {"random_seed": 1}), ("msat", {"random_seed": 2})],
                     incremental=True)

        Options specified in the Portfolio are shared among all
        solvers, e.g., in the first example all solvers will receive
        the option 'incremental=True'.

        One process will be used for each of the solvers.
        """
        ...

    def get_value(self, formula): ...
    def get_model(self):  # -> EagerModel:
        ...
