"""
This type stub file was generated by pyright.
"""

from pysmt.walkers.identitydag import IdentityDagWalker

class QuantifierEliminator:
    def __init__(self) -> None: ...
    def eliminate_quantifiers(self, formula):
        """
        Returns a quantifier-free equivalent formula of the given
        formula

        If explicit_vars is specified, an explicit enumeration of all
        the possible models for such variables is computed and
        quantifier elimination is performed on each disjunct
        separately.
        """
        ...

    def __enter__(self):  # -> Self:
        """Manage entering a Context (i.e., with statement)"""
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        """Manage exiting from Context (i.e., with statement)

        The default behaviour is to explicitly destroy the qelim to free
        the associated resources.
        """
        ...

    def exit(self):  # -> None:
        """Destroys the solver and closes associated resources."""
        ...

class ShannonQuantifierEliminator(QuantifierEliminator, IdentityDagWalker):
    """Quantifier Elimination using Shannon Expansion."""

    LOGICS = ...
    def __init__(self, environment, logic=...) -> None: ...
    def eliminate_quantifiers(self, formula): ...
    def walk_forall(self, formula, args, **kwargs): ...
    def walk_exists(self, formula, args, **kwargs): ...

class SelfSubstitutionQuantifierEliminator(QuantifierEliminator, IdentityDagWalker):
    """Boolean Quantifier Elimination based on Self-Substitution.

    Described in :
     "BDD-Based Boolean Functional Synthesis",
     Dror Fried, Lucas M. Tabajara, and Moshe Y. Vardi,
     CAV 2016
    """

    LOGICS = ...
    def __init__(self, environment, logic=...) -> None: ...
    def eliminate_quantifiers(self, formula): ...
    def self_substitute(self, formula, qvars, token): ...
    def walk_forall(self, formula, args, **kwargs):
        """Forall y . f(x, y) =>  f(x, f(x, 0))"""
        ...

    def walk_exists(self, formula, args, **kwargs):
        """Exists y . f(x, y) =>  f(x, f(x, 1))"""
        ...
