"""
This type stub file was generated by pyright.
"""

class SmtLibSolver:
    def set_logic(self, logic):
        """Defines the logic in use.

        E.g., set_logic("QF_LIA")

        Restrictions: Can be executed only once.

        :param logic: The logic in use
        :type logic:  String
        :returns: True on success,
                  False if the logic is not supported
        """
        ...

    def declare_fun(self, symbol):
        """Declare a function symbol.

        Restrictions: Only after set-logic.

        :param symbol: Symbol to be declared
        :type name:  Pysmt symbol
        :returns: None - might raise exceptions
        """
        ...

    def declare_const(self, symbol):
        """Declares a constant symbol.

        Restrictions: Only after set-logic.

        :param symbol: Symbol to be declared
        :type name:  Pysmt symbol
        :returns: None
        """
        ...

    def define_fun(self, name, args, rtype, expr):
        """Declare an interpreted function. Can be used to build abbreviations.

        Restrictions: Only after set-logic.

        :param name: Name of the function
        :type name:  String
        :param args: Name and Type of the arguments of the function
        :type args: List of tuples (name, type)
        :param rtype: Return type
        :type rtype: Sort
        :param expr: Expression to associate with the function
        :type expr: FNode
        :returns: None - might raise exceptions
        """
        ...

    def declare_sort(self, name, cardinality):
        """Declares a new sort with the given name and cardinality.

        Restrictions: Only after set-logic.

        :returns: None - might raise exception
        """
        ...

    def define_sort(self, name, args, sort_expr):
        """Declares a symbol as an abbreviation for a sort-expression.

        Restrictions: Only after set-logic.
        :returns: None - might raise exception
        """
        ...

    def assert_(self, expr, named=...):
        """Assert the given expression.

        Optionally provides a name to the terms.

        Restrictions: Only after set-logic.
        :returns: None - might raise exception
        """
        ...

    def get_assertions(self):
        """Returns a list of asserted expressions.

        Restrictions: Only after set-logic.
        """
        ...

    def check_sat(self):
        """Checks the satisfiability of the formula.

        Restrictions: Only after set-logic.

        :returns: SAT, UNSAT, Unknown
        """
        ...

    def get_proof(self):
        """Returns a proof of unsatisfiability.

        Restrictions: Requires option :produce-proofs to be set and can be
                      called only after check-sat returned unsat, if no
                      change to the assertion set occurred.

        Note: The structure of the returned proof is Solver dependent.

        """
        ...

    def get_unsat_core(self):
        """Returns the unsat cores.

        Restrictions: Requires option :produce-unsat-cores to be set true and can
                      be called only after check-sat returned unsat, if no
                      change to the assertion set occurred.

        Note: Requires elements to be named.
        """
        ...

    def get_values(self, exprs):
        """Returns the value of the expressions if a model was found.

        Restrictions: Requires option :produce-models to be set to true and can
                      be called only after check-sat returned sat or unknown,
                      if no change to the assertion set occurred.

        :type exprs: List of FNodes
        :returns: A dictionary associating to each expr a value
        :rtype: dict
        """
        ...

    def get_assignment(self):
        """Returns an assignment for the named terms.

        Restrictions: Requires option :produce-assignments to be set to true and
                      can be called only after check-sat returned sat or unknown
                      if no change to the assertion set occurred.

        Note: Requires elements to be named
        """
        ...

    def push(self, levels=...):
        """Push the current context of the given number of levels.

        Restrictions: after set-logic
        """
        ...

    def pop(self, levels=...):
        """Pop the context of the given number of levels.

        Restrictions: after set-logic
        """
        ...

    def get_option(self, name):
        """Gets the value of the given option from the solver."""
        ...

    def set_option(self, name, value):
        """Sets the given value for the option in the solver.

        SMTLIB-defined Options:

        +---------------------------+----------+---------+----------+
        | Name                      | Required | Type    | Default  |
        +===========================+==========+=========+==========+
        | print-success             | required | boolean | true     |
        | regular-output-channel    | required | string  | "stdout" |
        | diagnostic-output-channel | required | string  | "stderr" |
        | expand-definitions        | optional | boolean | false    |
        | interactive-mode          | optional | boolean | false    |
        | produce-proofs            | optional | boolean | false    |
        | produce-unsat-cores       | optional | boolean | false    |
        | produce-models            | optional | boolean | false    |
        | produce-assignments       | optional | boolean | false    |
        | random-seed               | optional | numeral | 0        |
        | verbosity                 | optional | numeral | 0        |
        +---------------------------+----------+---------+----------+
        """
        ...

    def get_info(self, name):
        """Gets the value of a given information."""
        ...

    def set_info(self, name, value):
        """Sets the value for a given information.

        Required (by SMT):
        * :name <string>
        * :authors <string>
        * :version <string>
        Optional
        * :error-behavior
        * :reason-unknown
        * :all-statistics
        """
        ...

    def exit(self):
        """Destroys the solver."""
        ...

class SmtLibIgnoreMixin(SmtLibSolver):
    def set_logic(self, logic):  # -> None:
        ...
    def declare_fun(self, symbol):  # -> None:
        ...
    def declare_const(self, symbol):  # -> None:
        ...
    def define_fun(self, name, args, rtype, expr):  # -> None:
        ...
    def declare_sort(self, name, cardinality):  # -> None:
        ...
    def define_sort(self, name, args, sort_expr):  # -> None:
        ...
    def assert_(self, expr, named=...):  # -> None:
        ...
    def get_assertions(self):  # -> None:
        ...
    def check_sat(self):  # -> None:
        ...
    def get_proof(self):  # -> None:
        ...
    def get_unsat_core(self):  # -> None:
        ...
    def get_values(self, exprs):  # -> None:
        ...
    def get_assignment(self):  # -> None:
        ...
    def push(self, levels=...):  # -> None:
        ...
    def pop(self, levels=...):  # -> None:
        ...
    def get_option(self, name):  # -> None:
        ...
    def set_option(self, name, value):  # -> None:
        ...
    def get_info(self, name):  # -> None:
        ...
    def set_info(self, name, value):  # -> None:
        ...
    def exit(self):  # -> None:
        ...

class SmtLibBasicSolver(SmtLibSolver):
    def assert_(self, expr, named=...): ...
    def check_sat(self): ...
    def get_values(self, exprs): ...
    def push(self, levels=...): ...
    def pop(self, levels=...): ...
    def exit(self): ...
