"""
This type stub file was generated by pyright.
"""

from pysmt.decorators import clear_pending_pop
from pysmt.solvers.options import SolverOptions

class Solver:
    """Represents a generic SMT Solver."""

    LOGICS = ...
    OptionsClass = SolverOptions
    def __init__(self, environment, logic, **options) -> None: ...
    def solve(self, assumptions=...):
        """Returns the satisfiability value of the asserted formulas.

        Assumptions is a list of Boolean variables or negations of
        boolean variables. If assumptions is specified, the
        satisfiability result is computed assuming that all the
        specified literals are True.

        A call to solve([a1, ..., an]) is functionally equivalent to::

          push()
          add_assertion(And(a1, ..., an))
          res = solve()
          pop()
          return res

        but is in general more efficient.

        Other convenience methods (is_sat, is_unsat, is_valid) are
        wrappers around this function.

        :returns: Whether the assertion stack is satisfiable
                  w.r.t. the given assumptions (if given)
        :rtype: bool
        """
        ...

    def get_model(self):
        """Returns an instance of Model that survives the solver instance.

        Restrictions: Requires option generate_models to be set to
                      true (default) and can be called only after
                      :py:func:`solve` (or one of the derived methods)
                      returned sat or unknown, if no change to the
                      assertion set occurred.

        """
        ...

    def is_sat(self, formula):
        """Checks satisfiability of the formula w.r.t. the current state of
        the solver.

        Previous assertions are taken into account.

        :type formula: FNode
        :returns: Whether formula is satisfiable
        :rtype: bool
        """
        ...

    def is_valid(self, formula):  # -> bool:
        """Checks validity of the formula w.r.t. the current state of the
        solver.

        Previous assertions are taken into account. See :py:func:`is_sat`

        :type formula: FNode
        :returns: Whether formula is valid
        :rtype: bool
        """
        ...

    def is_unsat(self, formula):  # -> bool:
        """Checks unsatisfiability of the formula w.r.t. the current state of
        the solver.

        Previous assertions are taken into account. See :py:func:`is_sat`

        :type formula: FNode
        :returns: Whether formula is unsatisfiable
        :rtype: bool
        """
        ...

    def get_values(self, formulae):  # -> dict[Any, Any]:
        """Returns the value of the expressions if a model was found.

        Requires option generate_models to be set to true (default)
        and can be called only after :py:func:`solve` (or to one of
        the derived methods) returned sat or unknown, if no change to
        the assertion set occurred.

        :type formulae: Iterable of FNodes
        :returns: A dictionary associating to each expr a value
        :rtype: dict

        """
        ...

    def push(self, levels=...):
        """Push the current context of the given number of levels.

        :type levels: int
        """
        ...

    def pop(self, levels=...):
        """Pop the context of the given number of levels.

        :type levels: int
        """
        ...

    def exit(self):  # -> None:
        """Exits from the solver and closes associated resources."""
        ...

    def reset_assertions(self):
        """Removes all defined assertions."""
        ...

    def add_assertion(self, formula, named=...):
        """Add assertion to the solver."""
        ...

    def add_assertions(self, formulae):  # -> None:
        ...
    def print_model(self, name_filter=...):
        """Prints the model (if one exists).

        An optional function can be passed, that will be called on each symbol
        to decide whether to print it.
        """
        ...

    def get_value(self, formula):
        """Returns the value of formula in the current model (if one exists).

        This is a simplified version of the SMT-LIB function get_values
        """
        ...

    def get_py_value(self, formula):
        """Returns the value of formula as a python type.

        E.g., Bool(True) is translated into True.
        This simplifies writing code that branches on values in the model.
        """
        ...

    def get_py_values(self, formulae):  # -> dict[Any, Any]:
        """Returns the values of the formulae as python types.

        Returns a dictionary mapping each formula to its python value.
        """
        ...

    def __enter__(self):  # -> Self:
        """Manages entering a Context (i.e., with statement)"""
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        """Manages exiting from Context (i.e., with statement)

        The default behaviour is "close" the solver by calling the
        py:func:`exit` method.
        """
        ...

class IncrementalTrackingSolver(Solver):
    """A solver that keeps track of the asserted formulae

    This class provides tracking of the assertions that are stored
    inside the solver, the last executed command and the last solving
    result.

    It requires the extending class to implement the following proxy
    methods:

    * _reset_assertions
    * _add_assertion
    * _solve
    * _push
    * _pop

    The semantics of each function is the same as the non-proxy
    version except for _add_assertion that is supposed to return a
    result (of any type) that will constitute the elements of the
    self.assertions list.
    """
    def __init__(self, environment, logic, **options) -> None:
        """See py:func:`Solver.__init__()`."""
        ...

    @property
    def last_command(self):  # -> str | None:
        """Returns the name of the last executed command"""
        ...

    @property
    def last_result(self):  # -> str | None:
        """Returns the result of the last call to solve().

        Returns True, False or "unknown": the last result of the last
        call to solve(). If solve has never been called, None is
        returned
        """
        ...

    @property
    @clear_pending_pop
    def assertions(self):  # -> list[Any]:
        """Returns the list of assertions that are still in the solver.

        Returns the list of results of calls to _add_assertion() that
        are still asserted in the solver
        """
        ...

    def reset_assertions(self):  # -> None:
        ...
    def add_assertion(self, formula, named=...):  # -> None:
        ...
    def solve(self, assumptions=...): ...
    def push(self, levels=...):  # -> None:
        ...
    def pop(self, levels=...):  # -> None:
        ...

class UnsatCoreSolver:
    """A solver supporting unsat core extraction"""

    UNSAT_CORE_SUPPORT = ...
    def get_unsat_core(self):
        """Returns the unsat core as a set of formulae.

        After a call to solve() yielding UNSAT, returns the unsat core
        as a set of formulae
        """
        ...

    def get_named_unsat_core(self):
        """Returns the unsat core as a dict of names to formulae.

        After a call to solve() yielding UNSAT, returns the unsat core as a
        dict of names to formulae
        """
        ...

class Model:
    """An abstract Model for a Solver.

    This class provides basic services to operate on a model returned
    by a solver. This class is used as superclass for more specific
    Models, that are solver dependent or by the EagerModel class.
    """
    def __init__(self, environment) -> None: ...
    def get_value(self, formula, model_completion=...):
        """Returns the value of formula in the current model (if one exists).

        If model_completion is True, then variables not appearing in the
        assignment are given a default value, otherwise an error is generated.

        This is a simplified version of the SMT-LIB function get_values .
        """
        ...

    def get_values(self, formulae, model_completion=...):  # -> dict[Any, Any]:
        """Evaluates the values of the formulae in the current model.

        Evaluates the values of the formulae in the current model
        returning a dictionary.
        """
        ...

    def get_py_value(self, formula, model_completion=...):
        """Returns the value of formula as a python type.

        E.g., Bool(True) is translated into True.
        This simplifies writing code that branches on values in the model.
        """
        ...

    def get_py_values(self, formulae, model_completion=...):  # -> dict[Any, Any]:
        """Returns the values of the formulae as python types.

        Returns the values of the formulae as python types. in the
        current model returning a dictionary.
        """
        ...

    def satisfies(self, formula, solver=...):  # -> bool:
        """Checks whether the model satisfies the formula.

        The optional solver argument is used to complete partial
        models.
        """
        ...

    @property
    def converter(self):  # -> None:
        """Get the Converter associated with the Solver."""
        ...

    @converter.setter
    def converter(self, value):  # -> None:
        ...
    def __getitem__(self, idx): ...
    def __str__(self) -> str: ...

class Converter:
    """A Converter implements functionalities to convert expressions.

    There are two key methods: convert() and back().
    The first performs the forward conversion (pySMT -> Solver API),
    the second performs the backwards conversion (Solver API -> pySMT)
    """
    def convert(self, formula):
        """Convert a PySMT formula into a Solver term."""
        ...

    def back(self, expr):
        """Convert an expression of the Solver into a PySMT term."""
        ...
