"""
This type stub file was generated by pyright.
"""

from pysmt.walkers.dag import DagWalker
from pysmt.walkers.generic import handles
from pysmt.walkers.identitydag import IdentityDagWalker
from pysmt.walkers.tree import TreeWalker

"""Provides walkers to navigate formulas.

Two types of walkers are provided: DagWalker and TreeWalker.

Internally, the Walkers have a dictionary that maps each FNode type to
the appropriate function to be called. When subclassing a Walker
remember to specify an action for the nodes of interest. Nodes for
which a behavior has not been specified will raise a
NotImplementedError exception.

Finally, an *experimental* meta class is provided called
CombinerWalker. This class takes a list of walkers and returns a new
walker that applies all the walkers to the formula. The idea is that
multiple information can be extracted from the formula by navigating
it only once.

"""
