"""
This type stub file was generated by pyright.
"""

from pysmt.walkers.tree import Walker

class DagWalker(Walker):
    """DagWalker treats the formula as a DAG and performs memoization of the
    intermediate results.

    This should be used when the result of applying the function to a
    formula is always the same, independently of where the formula has
    been found; examples include substitution and solving.

    Due to memoization, a few more things need to be taken into
    account when using the DagWalker.

    :func _get_key needs to be defined if additional arguments via
    keywords need to be shared. This function should return the key to
    be used in memoization. See substituter for an example.
    """
    def __init__(self, env=..., invalidate_memoization=...) -> None:
        """The flag ``invalidate_memoization`` can be used to clear the cache
        after the walk has been completed: the cache is one-time use.
        """
        ...

    def iter_walk(self, formula, **kwargs):
        """Performs an iterative walk of the DAG"""
        ...

    def walk(self, formula, **kwargs): ...
    def walk_true(self, formula, args, **kwargs):  # -> Literal[True]:
        """Returns True, independently from the children's value."""
        ...

    def walk_false(self, formula, args, **kwargs):  # -> Literal[False]:
        """Returns False, independently from the children's value."""
        ...

    def walk_none(self, formula, args, **kwargs):  # -> None:
        """Returns None, independently from the children's value."""
        ...

    def walk_identity(self, formula, **kwargs):
        """Returns formula, independently from the childrens's value."""
        ...

    def walk_any(self, formula, args, **kwargs):  # -> bool:
        """Returns True if any of the children returned True."""
        ...

    def walk_all(self, formula, args, **kwargs):  # -> bool:
        """Returns True if all the children returned True."""
        ...
