"""
This type stub file was generated by pyright.
"""

import sys

import pysmt.operators as op

if sys.version_info >= (3, 3): ...
else: ...

def nt_to_fun(o):  # -> str:
    """Returns the name of the walk function for the given nodetype."""
    ...

class handles:
    """Decorator for walker functions.

    Use it by specifying the nodetypes that need to be handled by the
    given function. It is possible to use groupd (e.g., op.RELATIONS)
    directly. ::

      @handles(op.NODE, ...)
      def walk_special(...):
         ...

    """
    def __init__(self, *nodetypes) -> None: ...
    def __call__(self, func): ...

class MetaNodeTypeHandler(type):
    """Metaclass used to intepret the nodehandler decorator."""
    def __new__(cls, name, bases, dct):  # -> Self:
        ...

class Walker(metaclass=MetaNodeTypeHandler):
    """Base Abstract Walker class.

    Do not subclass directly, use DagWalker or TreeWalker, instead.
    """
    def __init__(self, env=...) -> None: ...
    def set_function(self, function, *node_types):  # -> None:
        """Overrides the default walking function for each of the specified
        node_types with the given function
        """
        ...

    @classmethod
    def set_handler(cls, function, *node_types):  # -> None:
        """Associate in cls the given function to the given node_types."""
        ...

    @classmethod
    def super(cls, self, formula, *args, **kwargs):  # -> Any:
        """Call the correct walk_* function of cls for the given formula."""
        ...

    @handles(op.ALL_TYPES)
    def walk_error(self, formula, **kwargs):
        """Default function for a node that is not handled by the Walker.

        This tries to handle the node using the Dynamic Walker
        Function information from the environment. If this fails, then
        an UnsupportedOperatorError exception is given.

        """
        ...
