"""
This type stub file was generated by pyright.
"""

def open_(fname):  # -> BZ2File | TextIOWrapper[_WrappedBuffer]:
    """Transparently handle .bz2 files."""
    ...

def get_formula(script_stream, environment=...):
    """
    Returns the formula asserted at the end of the given script

    script_stream is a file descriptor.
    """
    ...

def get_formula_strict(script_stream, environment=...):
    """Returns the formula defined in the SMTScript.

    This function assumes that only one formula is defined in the
    SMTScript. It will raise an exception if commands such as pop and
    push are present in the script, or if check-sat is called more
    than once.
    """
    ...

def get_formula_fname(script_fname, environment=..., strict=...):
    """Returns the formula asserted at the end of the given script."""
    ...

class SmtLibExecutionCache:
    """Execution environment for SMT2 script execution"""
    def __init__(self, env) -> None: ...
    def bind(self, name, value):  # -> None:
        """Binds a symbol in this environment"""
        ...

    def unbind(self, name):  # -> None:
        """Unbinds the last binding of this symbol"""
        ...

    def define(self, name, parameters, expression):  # -> None:
        ...
    def get(self, name):  # -> Callable[..., Any] | None:
        """Returns the last binding for 'name'"""
        ...

    def update(self, value_map):  # -> None:
        """Binds all the symbols in 'value_map'"""
        ...

    def unbind_all(self, values):  # -> None:
        """UnBinds all the symbols in 'values'"""
        ...

class Tokenizer:
    """Takes a file-like object and produces a stream of tokens following
    the LISP rules.

    If interactive is True, the file reading proceeds char-by-char with
    no buffering. This is useful for interactive use for example with
    a SMT-Lib2-compliant solver

    The method add_extra_token allows to "push-back" a token, so that
    it will be returned by the next call to consume_token, instead of
    reading from the actual generator.

    """
    def __init__(self, handle, interactive=...) -> None: ...
    def add_extra_token(self, token):  # -> None:
        ...
    def consume_maybe(self):  # -> LiteralString | Literal['"']:
        """Consumes and returns a single token from the stream.
        If the stream is empty `StopIteration` is thrown"""
        ...

    def consume(self, msg=...):  # -> LiteralString | Literal['"']:
        """Consumes and returns a single token from the stream.
        If the stream is empty, a PysmtSyntaxError is thrown"""
        ...

    def raw_read(self):  # -> str:
        ...
    @property
    def pos_info(self):  # -> tuple[int | Any, int | Any | None] | None:
        ...
    @staticmethod
    def create_generator(reader):  # -> Generator[LiteralString | Any | Literal['"'], Any, None]:
        """Takes a file-like object and produces a stream of tokens following
        the LISP rules.

        This is the method doing the heavy-lifting of tokenization.
        """
        ...

    def char_iterator(self, handle):  # -> Generator[Any | Literal['\n', '\r'], Any, None]:
        ...

class SmtLibParser:
    """Parse an SmtLib file and builds an SmtLibScript object.

    The main function is get_script (and its wrapper
    get_script_fname).  This function relies on the tokenizer function
    (to split the inputs in token) that is consumed by the get_command
    function that returns a SmtLibCommand for each command in the
    original file.

    If the interactive flag is True, the file reading proceeds
    char-by-char with no buffering. This is useful for interactive use
    for example with a SMT-Lib2-compliant solver
    """
    def __init__(self, environment=..., interactive=...) -> None: ...
    def atom(self, token, mgr):  # -> Callable[..., Any]:
        """
        Given a token and a FormulaManager, returns the pysmt representation of
        the token
        """
        ...

    def get_expression(self, tokens):  # -> Callable[..., Any] | None:
        """
        Returns the pysmt representation of the given parsed expression
        """
        ...

    def get_script(self, script):  # -> SmtLibScript:
        """
        Takes a file object and returns a SmtLibScript object representing
        the file
        """
        ...

    def get_command_generator(self, script):  # -> Generator[SmtLibCommand | Any, Any, None]:
        """Returns a python generator of SmtLibCommand's given a file object
        to read from

        This function can be used interactively, and blocks until a
        whole command is read from the script.

        """
        ...

    def parse_model(self, script):  # -> tuple[dict[Any, Any], dict[Any, Any]]:
        """This function pasres the result of a `(get-model)` command and
        returns a model as a dictionary from non-function symbols to
        constant values and an interpretation for uninterpreted
        functions as a map from the function symbol to a
        FunctionInterpretation object.

        Example:
        ```
        model_source ="(model
          (define-fun b () Int 5)
          (define-fun a () Real 2)
          (define-fun f ((x0 Int)) Real (ite (> x0 5) 1 0.5))
        )"
        model_buf = StringIO(model_source)
        parser = SmtLibParser()
        model, interpretations = parser.parse_model(model_buf)
        ```
        gives:

        `model = {Symbol('a', INT): Int(5), Symbol('b', Real): Real(2)}`
        `interpretations = {Symbol('f', FunctionType(REAL, [INT])): fi}`

        where `fi = FunctionInterpretation([Symbol('x0', Int)], ITE(GT(Symbol('x0', Int), Int(5)), Real(1), Real(0.5)))`
        """
        ...

    def get_script_fname(self, script_fname):  # -> SmtLibScript:
        """Given a filename and a Solver, executes the solver on the file."""
        ...

    def parse_atoms(self, tokens, command, min_size, max_size=...):  # -> list[Any]:
        """
        Parses a sequence of N atoms (min_size <= N <= max_size) consuming
        the tokens
        """
        ...

    def parse_type(
        self, tokens, command, type_params=..., additional_token=...
    ):  # -> tuple[Any] | PartialType | Callable[..., Any]:
        """Parses a single type name from the tokens"""
        ...

    def parse_atom(self, tokens, command):
        """Parses a single name from the tokens"""
        ...

    def parse_params(self, tokens, command):  # -> list[Any]:
        """Parses a list of types from the tokens"""
        ...

    def parse_named_params(self, tokens, command):  # -> list[Any]:
        """Parses a list of names and type from the tokens"""
        ...

    def parse_expr_list(self, tokens, command):  # -> list[Any]:
        """Parses a list of expressions form the tokens"""
        ...

    def consume_opening(self, tokens, command):  # -> None:
        """Consumes a single '('"""
        ...

    def consume_closing(self, tokens, command):  # -> None:
        """Consumes a single ')'"""
        ...

    def get_assignment_list(self, script):  # -> list[Any]:
        """
        Parse an assignment list produced by get-model and get-value
        commands in SmtLib
        """
        ...

    def get_command(self, tokens):  # -> Generator[SmtLibCommand | Any, Any, None]:
        """Builds an SmtLibCommand instance out of a parsed term."""
        ...

class SmtLib20Parser(SmtLibParser):
    """Parser for SMT-LIB 2.0."""
    def __init__(self, environment=..., interactive=...) -> None: ...

class SmtLibZ3Parser(SmtLibParser):
    """
    Parses extended Z3 SmtLib Syntax
    """
    def __init__(self, environment=..., interactive=...) -> None: ...
