"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Optional

from pychc.solvers.witness import ProofFormat, UnsatWitness

class ProofCheckerOptions:
    """
    Options container for proof checkers.
    """
    def __init__(self, **_: object) -> None: ...
    def to_array(self) -> list[str]: ...
    def set_mode(self, mode: str) -> None: ...
    def set_flag(self, flag: str, enable: bool = ...) -> None: ...
    def set_option(self, option: str, value: object) -> None: ...

class ProofChecker(ABC):
    """
    Abstract base class for proof checkers.
    """

    NAME: str = ...
    OPTION_CLASS = ProofCheckerOptions
    def __init__(self, binary_dir: Optional[Path] = ..., **options) -> None: ...
    @abstractmethod
    def get_proof_format(self) -> Optional[ProofFormat]:
        """
        Get the proof format used by this proof checker, if any.
        """
        ...

    def validate_witness(self, witness: UnsatWitness, smt2file: Path, timeout: Optional[int] = ...) -> bool:
        """
        Validate the proof contained in the witness against the given smt2 file.
        """
        ...

    def validate(self, proof_file: Path, smt2file: Path, timeout: Optional[int] = ...) -> bool: ...
