"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

from pychc.solvers.proof_checker import ProofChecker
from pychc.solvers.witness import ProofFormat, Status
from pysmt.logics import Logic
from pysmt.smtlib.solver import SmtLibOptions, SmtLibSolver

class SMTSolverOptions(SmtLibOptions):
    """
    Options for SMTSolver extending PySMT's SmtLibOptions
    with proof support and `run` method.
    """

    PROOF_FORMATS: set[ProofFormat] = ...
    def __init__(self, **base_options) -> None: ...
    def set_produce_proofs(self, enable: bool = ..., proof_format: Optional[ProofFormat] = ...) -> None: ...
    def set_proof_format(self, proof_format: ProofFormat) -> None: ...
    def __call__(self, solver: SmtLibSolver):  # -> None:
        ...

class SMTSolver(SmtLibSolver):
    """
    Abstract SMT solver interface using SMT-LIB textual protocol.

    Inherits from pySMT's SmtLibSolver and adds `get_proof()` support.
    Implementations can override NAME/LOGICS and provide additional options.
    """

    NAME: str = ...
    LOGICS = ...
    OptionsClass = SMTSolverOptions
    def __init__(
        self,
        logic: Optional[Logic] = ...,
        binary_path: Optional[Path] = ...,
        cmd_args: Optional[list[str]] = ...,
        proof_checker: Optional[ProofChecker] = ...,
        **options,
    ) -> None: ...
    def recreate_process(self) -> None: ...
    def set_logic(self, logic: Logic) -> None: ...
    def get_logic(self) -> Logic: ...
    def set_timeout(self, timeout: Optional[int]) -> None: ...
    def set_proof_checker(self, proof_checker: Optional[ProofChecker]) -> None:
        """
        Set or change the proof checker used for validating proofs.
        """
        ...

    def get_proof_format(self) -> Optional[ProofFormat]: ...
    def reset_assertions(self):  # -> None:
        ...
    def push(self):  # -> None:
        ...
    def pop(self):  # -> None:
        ...
    def get_proof(self) -> str:
        """
        Request a proof/certificate from the solver using `(get-proof)`.
        """
        ...

    def delete_files(self) -> None: ...
    def get_smt2_file(self) -> Path: ...
    def get_proof_file(self) -> Path: ...
    def validate_proof(self):  # -> None:
        """
        Request a proof from the solver and validate it using the configured proof checker
        """
        ...

    def run(self, path: Path, timeout: Optional[int] = ...) -> Status:
        """
        Run the solver on the provided SMT-LIBv2 file.
        If the output is sat/unsat + something, the status will
        parsed and stored internally.
        If unsat, the following output is stored as the proof.
        Otherwise, PyCHCUnknownResultException is raised.
        """
        ...
