"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from enum import Enum
from pathlib import Path

from pysmt.substituter import FunctionInterpretation

class ProofFormat(str, Enum):
    ALETHE = ...
    LFSC = ...
    DOT = ...
    LEGACY = ...
    INTERMEDIATE = ...

class Witness(ABC):
    """Abstract witness produced by a solver."""
    @abstractmethod
    def serialize(self, path: Path) -> None:
        """Serialize the witness to a file."""
        ...

    @abstractmethod
    def serialize_to_string(self) -> str:
        """Serialize the witness to a string."""
        ...

class SatWitness(Witness):
    """
    SAT witness is an interpretation for the predicates.
    Stored as an interpreted formulae in pySMT FunctionInterpretation format.
    """
    @classmethod
    def load_from_text(cls, smt_text: str) -> SatWitness: ...
    @classmethod
    def load_from_file(cls, path: Path) -> SatWitness: ...
    def __init__(self, definitions: dict[str, FunctionInterpretation]) -> None: ...
    def serialize(self, path: Path) -> None:
        """Serialize the SAT witness to a file."""
        ...

    def serialize_to_string(self) -> str: ...

class UnsatWitness(Witness):
    """
    UNSAT witness (proof/certificate) produced by a solver.
    Stored as plain text along with its format.
    """
    def __init__(self, text: str, proof_format: ProofFormat) -> None: ...
    @classmethod
    def load_from_file(cls, path: Path, proof_format: ProofFormat) -> SatWitness: ...
    def serialize(self, path: Path) -> None:
        """Serialize the UNSAT witness to a file."""
        ...

    def serialize_to_string(self) -> str:
        """Serialize the UNSAT witness to a string."""
        ...

class Status(str, Enum):
    """Outcome of solving a CHC system."""

    SAT = ...
    UNSAT = ...
    UNKNOWN = ...
