"""
This type stub file was generated by pyright.
"""

class Annotations:
    """Handles and stores (key,value) annotations for formulae"""
    def __init__(self, initial_annotations=...) -> None: ...
    def add(self, formula, annotation, value=...):  # -> None:
        """Adds an annotation for the given formula, possibly with the
        specified value"""
        ...

    def remove(self, formula):  # -> None:
        """Removes all the annotations for the given formula"""
        ...

    def remove_annotation(self, formula, annotation):  # -> None:
        """Removes the given annotation for the given formula"""
        ...

    def remove_value(self, formula, annotation, value):  # -> None:
        """Removes the given annotation for the given formula"""
        ...

    def has_annotation(self, formula, annotation, value=...):  # -> bool:
        """Returns True iff the given formula has the given annotation. If
        Value is specified, True is returned only if the value is
        matching.
        """
        ...

    def annotations(self, formula):  # -> None:
        """Returns a dictionary containing all the annotations for the given
        formula as keys and the respective values. None is returned if
        formula has no annotations.
        """
        ...

    def all_annotated_formulae(self, annotation, value=...):  # -> set[Any]:
        """Returns the set of all the formulae having the given annotation
        key. If Value is specified, only the formula having the
        specified value are returned.
        """
        ...

    def __contains__(self, formula):  # -> bool:
        """Checks if formula has at least one annotation"""
        ...

    def __str__(self) -> str: ...
    def __getitem__(self, formula):  # -> None:
        ...
