"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

def check_sat_filter(log):
    """
    Returns the result of the check-sat command from a log.

    Raises errors in case a unique check-sat command cannot be located.
    """
    ...

class SmtLibCommand(namedtuple("SmtLibCommand", ["name", "args"])):
    def serialize(self, outstream=..., printer=..., daggify=...):  # -> None:
        """Serializes the SmtLibCommand into outstream using the given printer.

        Exactly one of outstream or printer must be specified. When
        specifying the printer, the associated outstream will be used.
        If printer is not specified, daggify controls the printer to
        be created. If true a daggified formula is produced, otherwise
        a tree printing is done.

        """
        ...

    def serialize_to_string(self, daggify=...):  # -> str:
        ...

class SmtLibScript:
    def __init__(self) -> None: ...
    def add(self, name, args):  # -> None:
        """Adds a new SmtLibCommand with the given name and arguments."""
        ...

    def add_command(self, command):  # -> None:
        ...
    def evaluate(self, solver):  # -> list[Any]:
        ...
    def contains_command(self, command_name):  # -> bool:
        ...
    def count_command_occurrences(self, command_name):  # -> int:
        ...
    def filter_by_command_name(self, command_name_set):  # -> Generator[Any, None, None]:
        ...
    def get_strict_formula(self, mgr=...): ...
    def get_declared_symbols(self):  # -> set[Any]:
        ...
    def get_define_fun_parameter_symbols(self):  # -> set[Any]:
        ...
    def get_last_formula(self, mgr=...):
        """Returns the last formula of the execution of the Script.

        This coincides with the conjunction of the assertions that are
        left on the assertion stack at the end of the SMTLibScript.
        """
        ...

    def to_file(self, fname, daggify=...):  # -> None:
        ...
    def serialize(self, outstream, daggify=...):  # -> None:
        """Serializes the SmtLibScript expanding commands"""
        ...

    def __len__(self):  # -> int:
        ...
    def __iter__(self):  # -> Iterator[Any]:
        ...
    def __str__(self) -> str: ...

def smtlibscript_from_formula(formula, logic=...):  # -> SmtLibScript:
    ...
def evaluate_command(cmd, solver):  # -> None:
    ...
