"""
This type stub file was generated by pyright.
"""

from pysmt.decorators import clear_pending_pop
from pysmt.solvers.solver import Solver, SolverOptions

class SmtLibOptions(SolverOptions):
    """Options for the SmtLib Solver.

    * debug_interaction: True, False
      Print the communication between pySMT and the wrapped executable
    """
    def __init__(self, **base_options) -> None: ...
    def __call__(self, solver):  # -> None:
        ...

class SmtLibSolver(Solver):
    """Wrapper for using a solver via textual SMT-LIB interface.

    The solver is launched in a subprocess using args as arguments of
    the executable. Interaction with the solver occurs via pipe.
    """

    OptionsClass = SmtLibOptions
    def __init__(self, args, environment, logic, LOGICS=..., **options) -> None: ...
    def set_option(self, name, value):  # -> None:
        ...
    def set_logic(self, logic):  # -> None:
        ...
    @clear_pending_pop
    def solve(self, assumptions=...):  # -> bool:
        ...
    @clear_pending_pop
    def reset_assertions(self):  # -> None:
        ...
    @clear_pending_pop
    def add_assertion(self, formula, named=...):  # -> None:
        ...
    @clear_pending_pop
    def push(self, levels=...):  # -> None:
        ...
    @clear_pending_pop
    def pop(self, levels=...):  # -> None:
        ...
    def get_value(self, item): ...
    def print_model(self, name_filter=...):  # -> None:
        ...
    def get_model(self):  # -> EagerModel:
        ...
